### ISSUE TITLE
need help, getting multi account to work

### ISSUE THREAD

**Issue by rj-d2** [newerton/bombcrypto-bot#100]
Hi

i hope someone can help me out getting multi account to work.

i have 2 browser windows next to each other, running 2 bombcrypto accounts in seperate profiles.
i changed the config to:

  multi_account:
    enable: true
    window_title: "bombcrypto"
    window_fullscreen: false

but when i run the bot i get:
Starting bot...
Terms and Service accepted in cache
Multi account DISABLE

then the bot uses both browser windows and gets confused.
why doesnt it say: Multi account ENABLED, what am i doing wrong?

**Comment by newerton** [comment]
@rj-d2 Did you save the config.yaml file after the change? How is the indentation of this file? The enable cannot be aligned in the same column as the name 'multi_account'.

![image](https://user-images.githubusercontent.com/4175945/155718303-3e0c991d-ba59-40e4-8862-b4e40101c8bd.png)

**Comment by rj-d2** [comment]
i did save the config.yaml 
the indentation is exactly as it was originally, i only changed enable from false to true.

![Screenshot_2022-02-25_16-35-56](https://user-images.githubusercontent.com/20203399/155743276-e520f094-e435-45ee-956c-0e4dba70f9be.png)

any other idea?
