### ISSUE TITLE
(Multi Account) - Username e password de acordo com ID ou Nome do Profile do Browser

### ISSUE THREAD

**Issue by santospv** [newerton/bombcrypto-bot#101]
Fala Newerton beleza?

Cara, notei que o bot atende a funcionalidade de username e password quando não é muilt acc...ficou show.

Mas quando for multi acc, sera que não da pra pegar pelo ID ou Nome do Profiler e alí atribuir os username passwords?

Não manjo de Phyton, mas ta aí uma sugestão mano, seria uma boa pra não utilizar a extensão da metamask e poder reduzir um pouco o processamento aqui com muilt acc. Valeu.

**Comment by newerton** [comment]
@santospv Já tiveram umas 3 issues sobre esse questionamento. O problema é as libs que identifica as janelas aberta, nenhuma delas consegue pegar o perfil logado do usuário, como por exemplo o email ou username. Em multi account é mais complexo isso, por que cada janela tem um ID (número de identificação), mas que é gerado aleatóriamente, então não tem como fixar um ID, nome, email ou nome de perfil, a vários usuários e senha do jogo.

**Comment by santospv** [comment]
Entendi, valeu @newerton .
