### ISSUE TITLE
Não funciona MultiAccount

### ISSUE THREAD

**Issue by robinhodemorais** [newerton/bombcrypto-bot#103]
Mesmo configurando no arquivo config.yaml a opção 
  multi_account:
    enable: true

ao iniciar o bot ele informa que o multiaccount está desabilitado.

![image](https://user-images.githubusercontent.com/13595347/156192351-99adc3ca-ceda-4cb9-9212-67f493b00c5c.png)

**Comment by newerton** [comment]
@robinhodemorais Está usando windows o linux?

**Comment by robinhodemorais** [comment]
linux

**Comment by newerton** [comment]
@robinhodemorais No linux não tem biblioteca de python para linux.

**Comment by robinhodemorais** [comment]
Amigo tem sim, dá uma pesquisada, valew por responder, consegui aqui rodar multi account.

**Comment by newerton** [comment]
@robinhodemorais Da uma pesquisada? Se você sabe se tem uma lib em python que identificar janelas no linux?

**Comment by robinhodemorais** [comment]
> @robinhodemorais Da uma pesquisada? Se você sabe se tem uma lib em python que identificar janelas no linux?

então eu não sou fera em python, minhas linguagens são outras,na vdd até matei essa materia na PÓS, então realmente não pesquisei se tem uma biblioteca especifica para identificar o browser, mas sempre tem um jeito para o nosso mundo de desenvolvimento, caso queira eu posso mandar o bot anterior que usava e o novo também para dar uma olhada como funciona, você que manja de python vai matar a ideia na hora.

**Comment by newerton** [comment]
@robinhodemorais Já testei 3 lib secundária com suporte a linux e mac, e nenhuma funciona. As libs que tem, precisa de contador, você precisa ficar colocando quantas contas vai usar, e o bot vai buscar a quantidade de janela aberta no linux.

**Comment by robinhodemorais** [comment]
> @robinhodemorais Já testei 3 lib secundária com suporte a linux e mac, e nenhuma funciona. As libs que tem, precisa de contador, você precisa ficar colocando quantas contas vai usar, e o bot vai buscar a quantidade de janela aberta no linux.

foi essa ai a solução mesmo, ficou show de bola com 3 contas aqui.
