### ISSUE TITLE
Bug Scroll page

### ISSUE THREAD

**Issue by Sneeazzz** [newerton/bombcrypto-bot#105]
![unknown](https://user-images.githubusercontent.com/54538662/156457307-0b758321-ed38-45c5-8f55-e70f4f62872e.png)

Hi I use the bot is it is great! But however at certain times when refreshing the page or I do not know who the bot scroll alone moves the window and prevents the bot from finding treasure hunt.
Do you have a solution for this or do I have to use another application?
Thank you for the answer🤗

**Comment by newerton** [comment]
@Sneeazzz This problem is from the page you are accessing, the bot does not have horizontal scrolling.

Use this page: https://app.bombcrypto.io/webgl/index.html
