### ISSUE TITLE
Conta com autenticações diferentes.

### ISSUE THREAD

**Issue by efdarkside** [newerton/bombcrypto-bot#106]
Seguinte,

Tenho duas contas, uma está somente na metamask e a outra está na metamask + trezor.

Na conta com a trezor eu coloquei login e senha no Bomb, pra facilitar pro bot, pois gerenciar essa conta com a Trezor + Bot sempre foi uma dor de cabeça pra mim.

Coloquei no config.yaml o login e senha no "auth", porém ele tenta autenticar na outra conta com esse login na outra metamask também... e o Bomb só permite criar 1 login por conta. Ou seja, ele acaba logando na mesma conta (a da trezor) nos dois navegadores.

Existe a possibilidade de setar autenticação diferente para navegadores diferentes? Uma com login e senha e outra conectando diretamente na metamask?

**Comment by newerton** [comment]
@efdarkside Estou analisando uma nova implementação para o login de usuário e senha para multiaccount. Mas esse modo vai ser mais trabalhoso para os usuários, por que vai precisar colocar o total de contas que será usada o bot, e depois para cada conta, vai ter que colocar o usuário e senha.

**Comment by efdarkside** [comment]
> @efdarkside Estou analisando uma nova implementação para o login de usuário e senha para multiaccount. Mas esse modo vai ser mais trabalhoso para os usuários, por que vai precisar colocar o total de contas que será usada o bot, e depois para cada conta, vai ter que colocar o usuário e senha.

Aí vai ficar massa. No aguardo de novidades!

Valeu amigo.

**Comment by efdarkside** [comment]
> @efdarkside Estou analisando uma nova implementação para o login de usuário e senha para multiaccount. Mas esse modo vai ser mais trabalhoso para os usuários, por que vai precisar colocar o total de contas que será usada o bot, e depois para cada conta, vai ter que colocar o usuário e senha.

Mano, testei sua nova versão com essa funcionalidade e rodou mega suave aqui.

Ainda tenho uma dúvida. Eu coloquei as duas janelas, lado a lado, mas o bot maximiza uma conta pra gerenciar ela, restaura a janela e maximiza a outra e assim sucessivamente. Não seria mais lógico ele gerenciar sem maximizar, já que com 2 janelas é possível o jogo ficar em 100% de zoom?

**Comment by newerton** [comment]
@efdarkside O problema de deixar para o bot gerenciar várias janelas, é que vai aparecer vários botões iguais na tela, ai o bot não vai identificar qual botão clicar. Por isso que é maximizado, para executar uma conta de cada vez.

**Comment by efdarkside** [comment]
> @efdarkside O problema de deixar para o bot gerenciar várias janelas, é que vai aparecer vários botões iguais na tela, ai o bot não vai identificar qual botão clicar. Por isso que é maximizado, para executar uma conta de cada vez.

Ah entendi, faz sentido!

Mas isso não afeta o farm? Ou a conta que fica sobreposta farma normalmente? E também achei que ele fica mudando de uma janela pra outra com muita frequência... é possível configurar para que ele deixe as duas janelas lá quietinhas, sei lá, por uns 5 minutos e aí sim ele faz o ciclo de maximizar uma, fazer o que tem q fazer, fazer na outra e deixar ambas restauradas?

**Comment by newerton** [comment]
@efdarkside Você pode colocar as janelas lado e lado, que o bot só vai maximizar uma por uma, não vai afetar o farm de outros, quando 1 janela está maximizada. 

Sobre o tempo, o bot faz isso, para identificar mais rapido qual navegador está com erro ou não, se tiver um pausa de 5 minutos, você pode ficar 5 minutos sem jogar, por que aparece aqueles erros chatos de dados não sincronizados com o servidor.

**Comment by efdarkside** [comment]
> @efdarkside Você pode colocar as janelas lado e lado, que o bot só vai maximizar uma por uma, não vai afetar o farm de outros, quando 1 janela está maximizada.
> 
> Sobre o tempo, o bot faz isso, para identificar mais rapido qual navegador está com erro ou não, se tiver um pausa de 5 minutos, você pode ficar 5 minutos sem jogar, por que aparece aqueles erros chatos de dados não sincronizados com o servidor.

Show mano, muito obrigado pelas infos e parabéns pelo trabalho!

**Comment by newerton** [comment]
Valeu, obrigado.
