### ISSUE TITLE
Desativar mult account

### ISSUE THREAD

**Issue by pedrowarlock** [newerton/bombcrypto-bot#110]
Peguei um config novo, coloquei 'false' no mult account, mas mesmo assim ele inicia com mult account e da um crash, e a opção de login por senha também não está funcionando, mesmo ativando, ele faz login pelo metamask.

PS: muito obrigado pelo seu projeto, ta de parabéns.

![Captura de tela de 2022-03-04 13-16-59](https://user-images.githubusercontent.com/2616950/156800344-85b48f56-f113-4472-9155-acb20e82dbf3.png)

**Comment by newerton** [comment]
@pedrowarlock Você atualizou seu config.yaml? Agora tem 2 itens que foi adicionado lá. E agora você precisa criar um accounts.yaml

https://github.com/newerton/bombcrypto-bot/blob/main/docs/README_pt-br.md#auth-with-user-and-pass

**Comment by ruanzxto** [comment]
O meu aqui está dando esse erro, e já botei login no accounts ![PXL_20220304_143750547.jpg](https://user-images.githubusercontent.com/97133292/156813866-9e086fdf-e06a-4c41-b70d-faa2418583c9.jpg)

**Comment by ruanzxto** [comment]
> O meu aqui está dando esse erro, e já botei login no accounts ![PXL_20220304_143750547.jpg](https://user-images.githubusercontent.com/97133292/156813866-9e086fdf-e06a-4c41-b70d-faa2418583c9.jpg)

E multiaccount tá desativado porém da ativado

**Comment by newerton** [comment]
@ruanzxto Acabei de fazer uma correção no src/multi_account.py, atualiza somente ele ou executa o git pull, se estiver usando git no seu computador.
