### ISSUE TITLE
Controle por raridade

### ISSUE THREAD

**Issue by ghost** [newerton/bombcrypto-bot#113]
@newerton, reparei que nos arquivos de imagem do bot tem uma pasta de classificação por raridade dos heróis. Tem alguma previsão de quando (caso seja possível) esse controle de mandar trabalhar por raridade vai ser adicionado ao bot?

**Comment by newerton** [comment]
@VGNChris Sim, iniciei o desenvolvimento, mas não conclui por que nas minhas contas só tenho Raro e Super Raro, agora com acesso por username e password, talvez eu consiga alguma conta de alguem para fazer essa nova implementação.
