### ISSUE TITLE
Comandos /bcoin

### ISSUE THREAD

**Issue by ruanzxto** [newerton/bombcrypto-bot#114]
Comando /bcoin tá retornando apenas a imagem da pasta temp, ele faz o processo pra gerar uma nova imagem porém acho que não tá tirando, ele também não tá gerando a quantidade via texto

**Comment by ruanzxto** [comment]
> Comando /bcoin tá retornando apenas a imagem da pasta temp, ele faz o processo pra gerar uma nova imagem porém acho que não tá tirando, ele também não tá gerando a quantidade via texto 

![Screenshot_2022-03-04-20-05-08-536_org.telegram.messenger.jpg](https://user-images.githubusercontent.com/97133292/156853951-6499f72d-788c-4b66-a97b-520be43f282a.jpg) essa imagem foi gerada antes da atualização porém tá sendo enviada agora

**Comment by newerton** [comment]
@ruanzxto Você atualizou o bot? Não é mais essa imagem que mostra o total de bcoins que vc tem no jogo.

**Comment by ruanzxto** [comment]
Atualizei hoje era umas 13:30 da tarde

**Comment by newerton** [comment]
Qual a sua versão no arquivo config/version.yaml ?

**Comment by ruanzxto** [comment]
config_file: "1.8.0"

**Comment by ruanzxto** [comment]
Ele faz todo processo certo, mas na hora de salvar a imagem na temp pra enviar ele não salva, e aí não reconhece também os números do print igual antes que enviava imagem e texto

**Comment by newerton** [comment]
Atualiza para 1.8.1, que é a atualização do report.
