### ISSUE TITLE
How to config Multi-accounts ?

### ISSUE THREAD

**Issue by Noha2a** [newerton/bombcrypto-bot#115]
Hello,

First of all thanks for the bot, it really helped me to farm 24/24 7/7 !

But now I got a second account and I can't make it works with both of my accounts..

Can someone explain me what to do/write inside the config file please ? Thank you

**Comment by newerton** [comment]
@Noha2a Did you update the bot? What is your version in version.yaml?

**Comment by Noha2a** [comment]
Yes the bot is updated, version 1.8.1

**Comment by newerton** [comment]
You need to set the number of accounts you will use in max_accounts, and then rename the EXAMPLE-accounts.yaml file to accounts.yaml.
