### ISSUE TITLE
Várias contas desativadas

### ISSUE THREAD

**Issue by MarcosCaique** [newerton/bombcrypto-bot#116]
boa noite, desculpe pelo inglês ruim, vou usar o tradutor 😅 Como faço para ativar uma conta mult? meu bot está atualizado 1.8.1 Configurei o log e a senha e também a conta múltipla, como na imagem abaixo, mas mesmo assim o bot começa com essa função desativada, você pode me ajudar
![Uploading image.jpg…]()

**Comment by newerton** [comment]
@MarcosCaique Deu erro na sua imagem. Para ativar o multiacc, você precisa setar o max_account, habilitar o multi_account, e setar as contas em accounts.yaml.

**Comment by MarcosCaique** [comment]
set mult account: Ok
the accounts in accounts.yaml : Ok

I don't know where to activate the mult account.

**Comment by MarcosCaique** [comment]
![4C5053A7-6C00-4A7F-BF31-91C9AC6DE7FD](https://user-images.githubusercontent.com/98467007/156862830-fb3e8378-67f1-4bfe-863b-bca20aed2b7e.jpeg)

**Comment by newerton** [comment]
multi_account:
    enable: true
