### ISSUE TITLE
Bot está funcionando somente em uma das paginas

### ISSUE THREAD

**Issue by kendikaku** [newerton/bombcrypto-bot#117]
bot não está sendo executado nas duas paginas,
sempre usei e agora está dando esse problema.
ele funciona somente em uma das contas, na outra nao.

**Comment by newerton** [comment]
@Japa18244 Ainda continua funcionando em multiacc.

https://github.com/newerton/bombcrypto-bot/blob/main/docs/README_pt-br.md#auth-with-user-and-pass
