### ISSUE TITLE
Erro ao executar 

### ISSUE THREAD

**Issue by monoufuuma** [newerton/bombcrypto-bot#118]
Grande @newerton ! , brother estou tendo esse erro ao executar o bot. Poderia por gentileza me dar um help?
![Capturar](https://user-images.githubusercontent.com/98677990/157171143-9a0c242c-5fd1-41ec-b792-b7982bc8391f.PNG)

Quero usar apenas uma conta.

**Comment by newerton** [comment]
Executa: pip install -r requirements.txt
