### ISSUE TITLE
Falha ao exportar total de bcoins

### ISSUE THREAD

**Issue by ruanzxto** [newerton/bombcrypto-bot#120]
![image](https://user-images.githubusercontent.com/97133292/159001519-79d60d53-1733-4835-87c3-d5800ebd93be.png)

ao retornar os bcoins via texto no telegram ele esta sempre mandando 35 bcoins mesmo tendo mais e na imagem tendo 37

**Comment by newerton** [comment]
@ruanzxto Você está com a útlima versão do bot? Aqui está reconhecendo todos os digitos. Pode ser que o jogo mudou a resolução dos números.

Muda o thresold de 0.94 para 0.91
https://github.com/newerton/bombcrypto-bot/blob/main/src/bcoins.py#L93

**Comment by ruanzxto** [comment]
alterado como pediu, reiniciei o bot
esperando terminar o ultilmo bau (por sinal é de chave kkk)

**Comment by newerton** [comment]
Ai demora mesmo hehe
Essa semana apareceu um mapa com 2 bau chave e 3 bau azul, ficou a tarde inteira até de noite.

**Comment by ruanzxto** [comment]
Deu certo! Gênio!
