### ISSUE TITLE
Multi account enabled error

### ISSUE THREAD

**Issue by Itsmetitan** [newerton/bombcrypto-bot#125]
Versions
  Local
    App: 1.9.0
    Config File: 1.9.0
  GitHub
    App: 1.9.0
    Config File: 1.9.0

Press Enter to start the bot...

2022-04-03 20:17:24 - 🤖 Starting bot...
2022-04-03 20:17:27 - ✅ Terms and Service accepted in cache
2022-04-03 20:17:28 - 🧾 Multi account enabled
Traceback (most recent call last):
  File "C:\bombcrypto-bot-main\index.py", line 50, in <module>
    main()
  File "C:\bombcrypto-bot-main\index.py", line 36, in main
    multi_account.start()
  File "C:\bombcrypto-bot-main\src\multi_account.py", line 53, in start
    self.botMultiAccount()
  File "C:\bombcrypto-bot-main\src\multi_account.py", line 89, in botMultiAccount
    total_accounts = len(self.accounts)
TypeError: object of type 'NoneType' has no len()

C:\bombcrypto-bot-main>

**Comment by Itsmetitan** [comment]
In previous version 1.8.3

app:
  theme: "default"
  verify_version: true
  emoji: true
  terminal_colorful: true
  run_time_app: 1
  monitor_to_use: 1
  captcha: false
  speed: "fast"
  authenticate: false
  max_accounts: 10
  multi_account:
    enable: true
    window_title: "bombcrypto"
    window_fullscreen: true
    
    It work's fine with me with 10 accounts, but I'm using the Metamask login.

**Comment by newerton** [comment]
@Itsmetitan Sorry! Fix now!

**Comment by sampaioops** [comment]
I have the same problem.. I solved it:
in multi_account.py
before
` self.accounts = None`
after
` self.accounts = Config().accounts()`

@newerton Can I open a pull request?

**Comment by sampaioops** [comment]
I spoke too late

**Comment by newerton** [comment]
> In previous version 1.8.3
> 
> app: theme: "default" verify_version: true emoji: true terminal_colorful: true run_time_app: 1 monitor_to_use: 1 captcha: false speed: "fast" authenticate: false max_accounts: 10 multi_account: enable: true window_title: "bombcrypto" window_fullscreen: true
> 
> ```
> It work's fine with me with 10 accounts, but I'm using the Metamask login.
> ```

I recommend always using login with username and password, authentication is faster.

**Comment by newerton** [comment]
> I have the same problem.. I solved it: in multi_account.py before ` self.accounts = None` after ` self.accounts = Config().accounts()`
> 
> @newerton Can I open a pull request?

I've fixed it! Thank you!

**Comment by newerton** [comment]
> I have the same problem.. I solved it: in multi_account.py before ` self.accounts = None` after ` self.accounts = Config().accounts()`
> 
> @newerton Can I open a pull request?

Removed the ```self.accounts = None```, I am no longer calculating the maximum amount of the account, the calculation is now done by the amount of the account within accounts.yaml

**Comment by sampaioops** [comment]
> > I have the same problem.. I solved it: in multi_account.py before ` self.accounts = None` after ` self.accounts = Config().accounts()`
> > @newerton Can I open a pull request?
> 
> Removed the `self.accounts = None`, I am no longer calculating the maximum amount of the account, the calculation is now done by the amount of the account within accounts.yaml

Good, I prefer it that way too, the first time I used it I saw that one responsibility was interfering with the other...
