### ISSUE TITLE
Bug ao enviar para House

### ISSUE THREAD

**Issue by abnercorps** [newerton/bombcrypto-bot#127]
Ao enviar os herois para casa ( Epic e Super-rare ) . Está com o seguinte bug 

Essa e a imagem dos primeiros herois. O bot clica corretamente para enviar o super-raro para House
![send_home_1](https://user-images.githubusercontent.com/50032328/161434094-02155e6a-a42a-46c8-ae3c-3a3022bfd11a.png)

Essa e a imagem da "pagina" seguinte dos herois. O bot envia o primeiro super-raro. Depois o jogo atualiza a posição dos herois
![send_home3](https://user-images.githubusercontent.com/50032328/161434090-b264a692-2a3a-42f6-85e6-4c96e45c96a5.png)
Ficando conforme a imagem abaixo. Nessa hora o bot clica no heroi RARO, que era a posicao do heroi Epic. rs
![send_home4](https://user-images.githubusercontent.com/50032328/161434087-3c1f5cd8-47e6-464f-a11e-aa332c8921e3.png)

Teria como corrigir isso ?
** Poderia ter uma opcao no arquivo de conf  para "checar" o envio dos herois para casa ?

att

**Comment by newerton** [comment]
@abnercorps Não tem como chegar heróis na casa, por que não tem lista na casa. Esse erro identifiquei quando estava desenvolvendo, esse tipo de problema ocorre caso o jogo esteja lento também, fazendo com que o bot clica 2x no mesmo botão.

Uma solução é fazer o bot clicar debaixo pra cima, assim evita do heróis subir na lista e o bot perder a referência de click.

**Comment by brim001** [comment]
Além desse "bug", tenho outro que estou enfrentando. 
Considerando um tiny house 4 lugares, o bot clica para enviar HOME e já tem 3 heróis, ao clicar no quarot que será  direcionado ao HOME, o servidor está lento e assim o botão HOME ainda continua ativo. Quando ele passa para o próximo herói, o bot clica em HOME novamente e o jogo aparece uma tela avisando que não tem esse recurso (Casa para 5) e precisa comprar uma casa. 
Poderia implementar algo para clicar no "X" do aviso.

**Comment by newerton** [comment]
@abnercorps Consegue me mandar mensagem no telegram? https://t.me/newerton

**Comment by abnercorps** [comment]
ja te adicionei

Em sáb., 9 de abr. de 2022 às 14:43, Newerton ***@***.***>
escreveu:
