### ISSUE TITLE
Janelas lado a lado

### ISSUE THREAD

**Issue by Leocmgb** [newerton/bombcrypto-bot#133]
Como configurar o bot para utilizar janelas lado a lado?

**Comment by newerton** [comment]
@Leocmgb Você consegue colocar as janelas lado a lado, mas o bot vai operar 1 janela por vez. Ele vai maximizar 1 janela por vez, e depois restaurar para a posição original. Para trabalhar com várias janelas, você precisa configurar vários perfil no chrome.
