### ISSUE TITLE
Multiple accounts not changing windows

### ISSUE THREAD

**Issue by Itsmetitan** [newerton/bombcrypto-bot#135]
Good day! Issue on multiple accounts not changing windows . I'm using Firefox

**Comment by newerton** [comment]
Multi account does not work by TAB. Only for multiple windows.

**Comment by Itsmetitan** [comment]
O sorry, i mean not changing windows ✌️

**Comment by newerton** [comment]
@Itsmetitan You need to register your accounts on accounts.yaml, the bot will get the amount of accounts and will manage the total number of open windows. For example: If you have 10 accounts, you need to open 10 game windows.

**Comment by Itsmetitan** [comment]
Awesome! Working now. Thank you & more powers. 🙏

**Comment by newerton** [comment]
@Itsmetitan Thank you 😻
