### ISSUE TITLE
A Macro do Sunflower ja está funcional?

### ISSUE THREAD

**Issue by jeffersonmdias** [newerton/bombcrypto-bot#137]
A Macro do Sunflower ja está funcional? 
Desculpa perguntar aqui, mas não consegui perguntar no do próprio sunflower que você postou.

**Comment by newerton** [comment]
@legnatv Ainda não, deixei funcionando de ontem para hoje, e ele ficou bugado em 1 espaço para plantar, estou testando aqui. Quando liberar eu te comunico aqui.

**Comment by jeffersonmdias** [comment]
Obrigado, estarei aguardando ;D
