### ISSUE TITLE
Heros tô work

### ISSUE THREAD

**Issue by ruanzxto** [newerton/bombcrypto-bot#138]
Atualizei agora o bot e ao iniciar não está colocando os heróis pra trabalhar

**Comment by newerton** [comment]
@ruanzxto Como está a configuração do seu config.yaml? Colocou somente os que estão com a barra de stamina verde?

Já sabe como funciona o bot, é por reconhecimento de imagem, então diminui o threshold do botão WORK
[threshold](https://github.com/newerton/bombcrypto-bot/blob/main/config/EXAMPLE-config.yaml#L31)
