### ISSUE TITLE
[Telegram] Bot enviando sempre o mesmo print após a última atualização

### ISSUE THREAD

**Issue by rodrigoomuller** [newerton/bombcrypto-bot#144]
Após a última atualização de hoje (1.9.4) o bot passou a enviar sempre o mesmo print, de ontem, quando minha conta ainda tinha 100 SEN nela. A leitura das quantidades mineradas está ok mas o print do mapa de todas contas é o mesmo.

**Comment by newerton** [comment]
@rodrigoomuller Ele está enviando mesmo print quando passa de mapa ou no comando /tokens?

**Comment by rodrigoomuller** [comment]
Quando passa de mapa. Tenho 4 contas e ele está mandando o mesmo print faz 2 dias (conferi e foi até antes da última atualização que começou a acontecer.

https://imgur.com/a/0ID2sHN

**Comment by newerton** [comment]
@rodrigoomuller Se você estiver usando a página do jogo com banners, tem que se atentar a esse botão de fullscreen.
![image](https://user-images.githubusercontent.com/4175945/163690180-8a6e37a6-d136-4530-8503-e99fb915d9f7.png)

Ele precisa está visivel, por que o bot usa esse botão como referência para tirar print do seu mapa. Se o bot não conseguir tirar o print, ele envia sempre o último.

**Comment by rodrigoomuller** [comment]
Ahhh saquei, tem que mover mais pra esse canto então? Ou como resolver?

**Comment by newerton** [comment]
Coloquei no README, 2 plugins do chrome/firefox/edge/brave para limpar essa página

https://github.com/newerton/bombcrypto-bot/#clean-page

**Comment by rodrigoomuller** [comment]
Perfeito! Obrigado!!
