### ISSUE TITLE
Multi account: bot only accepts the first "terms agreement" account 

### ISSUE THREAD

**Issue by johndavemanuel** [newerton/bombcrypto-bot#146]

**Comment by johndavemanuel** [comment]
the 2nd account and the rest don't, need to manually click accept each

**Comment by newerton** [comment]
This functionality was only added in 1 account, in multiaccount the message 'Terms and Service accepted in cache' will always appear, why do you need to add this code in the loop.

But there is not only this message, there is another term which is security information, when you use username and password.
