### ISSUE TITLE
COMANDOS TELEGRAM

### ISSUE THREAD

**Issue by 041gh0stt** [newerton/bombcrypto-bot#147]
Alguém poderia me enviar todos os comandos que são possiveis utilizar no Bot do telegram? Não estou encontrando aqui no Github

**Comment by newerton** [comment]
@041gh0stt Digita / na campo de mensagem que vai aparecer todos os comandos.

**Comment by 041gh0stt** [comment]
> @041gh0stt Digita / na campo de mensagem que vai aparecer todos os comandos.

Você diz no campo de mensagem do Telegram? Que se for, eu digitei aqui mas não me retornou nada :(
