### ISSUE TITLE
COMANDO PARA VER SALDO EM MULTI ACCOUNTS

### ISSUE THREAD

**Issue by 041gh0stt** [newerton/bombcrypto-bot#148]
Qual comando utilizo para ver o saldo em multi accounts? Tentei o /tokens mas não está funcionando e meu telegram não me informa quais comandos o bot tem

**Comment by newerton** [comment]
Para multi account nenhum funciona, por que o bot interrompe o farm, para executar o comando em todas as janelas. Você só vai receber os tokens no final de cada mapa.
