### ISSUE TITLE
Consigo abrir várias janelas em 50%?

### ISSUE THREAD

**Issue by jeffersonmdias** [newerton/bombcrypto-bot#149]
Consigo abrir várias janelas em 50%?
Ou seria lado a lado 100%?

**Comment by newerton** [comment]
@legnatv O modo multiacc, você pode deixar as janelas até minimizada. Mas no caso de lado a lado, você não pode mexer no zoom do sistema operacional e nem no browser, sempre todos tem que está 100%. Se for deixar lado a lado, não tem problema do browser está cortando uma parte do jogo, o bot vai sempre maximizar a janela, fazer as operações, e depois voltar a janela ao estado atual anterior que ela estava.

**Comment by jeffersonmdias** [comment]
> @legnatv O modo multiacc, você pode deixar as janelas até minimizada. Mas no caso de lado a lado, você não pode mexer no zoom do sistema operacional e nem no browser, sempre todos tem que está 100%. Se for deixar lado a lado, não tem problema do browser está cortando uma parte do jogo, o bot vai sempre maximizar a janela, fazer as operações, e depois voltar a janela ao estado atual anterior que ela estava.

Deixando lado a lado perde a eficiência? tinha uma história que se deixar em segundo plano o farm é piorado, atualmente tenho 8 contas rodando em um RDP, e estou pensando em começar a usar o seu bot, o vip que eu pago está acabando hoje e não estou querendo continuar pagando lá, não ta compensando mais.

**Comment by newerton** [comment]
> > @legnatv O modo multiacc, você pode deixar as janelas até minimizada. Mas no caso de lado a lado, você não pode mexer no zoom do sistema operacional e nem no browser, sempre todos tem que está 100%. Se for deixar lado a lado, não tem problema do browser está cortando uma parte do jogo, o bot vai sempre maximizar a janela, fazer as operações, e depois voltar a janela ao estado atual anterior que ela estava.
> 
> Deixando lado a lado perde a eficiência? tinha uma história que se deixar em segundo plano o farm é piorado, atualmente tenho 8 contas rodando em um RDP, e estou pensando em começar a usar o seu bot, o vip que eu pago está acabando hoje e não estou querendo continuar pagando lá, não ta compensando mais.

Então, o jogo não pode fica atras de outra janela ou minimizado, eu me recordo que tinha uma opção no chrome que você desativavá que o chrome parava de mandar o status para o jogo de status minimizado ou de segundo plano. Mas o bot ele vai alternando várias vezes entre os browser, e eu acho que não terá esse problema.

**Comment by jeffersonmdias** [comment]
> não

entendi, blz, hoje vou começar a usar o seu bot, obrigado pelos esclarecimentos.
