### ISSUE TITLE
Erro na versão 1.9.5

### ISSUE THREAD

**Issue by MaisUmGoncalves** [newerton/bombcrypto-bot#150]
Bom dia,

Após atualizar para a versão 1.9.5 o bot trava meu pc ao iniciar.
Se volto para versão 1.9.0 roda de boa.

PS: estou executando o bot em um PC da Xuxa =-) Celerom bem fraquinho.

![image](https://user-images.githubusercontent.com/72089071/163824496-073cf1b1-b878-4979-8ab3-6b0049343222.png)

**Comment by newerton** [comment]
@MaisUmGoncalves Você não ativou o logs > show_print ?
Aqui estou rodando o bot em 1 conta, no laptop de 2GB de RAM, quantos GB tem ae?

Recomendo abrir o jogo primeiro, na tela de Connect, você ativa o bot.

**Comment by Leovazrj** [comment]
@newerton ola amigo como vai? Como posso fazer para atualizar o meu para essa versao 1.9.5, estou usando a 1.9.0. Desde ja lhe agradeço
