### ISSUE TITLE
Multi Account Parou

### ISSUE THREAD

**Issue by LeandroBraccio** [newerton/bombcrypto-bot#151]
Bom dia,

Atualizei o bot, percebi que a linha que colocava o total de contas foi removida. Mesmo assim mantive multi account como true na frente do enable. Mas o bot não está trocando as telas. Está parada só em uma. Tem alguma coisa nessa nova versão que precisa mexer em mais algum lugar?

Minha config está assim:

app:
  theme: "default"
  verify_version: true
  emoji: true
  terminal_colorful: true
  run_time_app: 1
  monitor_to_use: 1
  captcha: false
  speed: "fast"
  authenticate: false
  multi_account:
    enable: true
    window_title: "bombcrypto"
    window_fullscreen: true

time_intervals:
  send_heroes_for_work: [30, 35]
  refresh_heroes_positions: [3, 4]

chests:
  values:
    divide: 2
    chest_01: 0.01425
    chest_02: 0.03250
    chest_03: 0.16250
    chest_04: 0.32500

threshold:
  default: 0.7
  error_message: 0.7
  back_button: 0.9
  work_button: 0.9
  home_enable_button: 0.98
  heroes_green_bar: 0.9
  heroes_red_bar: 0.9
  heroes_full_bar: 0.9
  heroes_send_all: 0.9
  heroes_rest_all: 0.9
  chest: 0.65
  jail: 0.8
  auth_input: 0.9
  heroes:
    common: 0.8
    rare: 0.8
    super_rare: 0.8
    epic: 0.8
    legend: 0.8
    super_legend: 0.8

heroes:
  mode: "green"
  list:
    scroll_attempts: 3

offsets:
  work_button_green: [120, 140]
  work_button_full: [90, 110]
  house_button: [260, 280]

metamask:
  enable: false
  password: ""

services:
  telegram: true

log:
  save_to_file: false
  console: false
  show_print: false

**Comment by newerton** [comment]
@LeandroBraccio Qual versão é seu bot? Não fiz alteração em multiaccount faz tempo. Percebeu que o jogo alterou o banner do treasure hunt?

**Comment by LeandroBraccio** [comment]
Eu estava usando a versão 1.8.0 até que resolvi atualizar para a versão atual 1.9.5. Sei que saiu a 1.9.6 referente ao banner, mas eu mesmo atualizei a imagem na pasta.

**Comment by newerton** [comment]
Em que momento o bot para? Ele não chega a maximizar a janela?

**Comment by LeandroBraccio** [comment]
Quando starto o bot, ele da alt+tab em alguma janela do bomb, coloca os herois para trabalhar, entra no modo caça ao tesouro e fica parado no mapa...não troca de janela para fazer o mesmo processo na minha outra conta.

**Comment by newerton** [comment]
Então está certo, o bot fica parado no mapa esperando os tempos do send_heroes_for_work e o refresh_heroes_positions, quantos minutos você colocou para o refresh_heroes_positions ? Esse tempo que vai determinar a troca de janela, quando o bot fizer todas as operações.

No terminal aparece algum erro?

**Comment by LeandroBraccio** [comment]
Não aparece erro. Realmente, ele faz o refresh dos heroes, mas de uma conta só. Ele não fica intercalando entre as duas que tenho. Antes, pelo menos na versão 1.8.0 ele fica trocando de tela a cada 3 seg, creio eu que era pra manter a janela ativa para o bomb não ficar inativo.

**Comment by LeandroBraccio** [comment]
Era pra supostamente funcionar em multi account mesmo sem a linha max_accounts: ? Antes eu setava o numero 2, ficando assim max_accounts: 2

**Comment by LeandroBraccio** [comment]
Tentei intercalar aqui manualmente trocando para outra tela do bomb, deu o seguinte erro no bot:

2022-04-19 11:21:02 - 🪟  Browser Active: Bombcrypto - Google Chrome
Traceback (most recent call last):
  File "C:\bombcrypto-bot-main-2\index.py", line 51, in <module>
    main()
  File "C:\bombcrypto-bot-main-2\index.py", line 37, in main
    multi_account.start()
  File "C:\bombcrypto-bot-main-2\src\multi_account.py", line 54, in start
    self.botMultiAccount()
  File "C:\bombcrypto-bot-main-2\src\multi_account.py", line 113, in botMultiAccount
    self.activeWindow(last, window)
  File "C:\bombcrypto-bot-main-2\src\multi_account.py", line 196, in activeWindow
    window.activate()
  File "C:\bombcrypto-bot-main-2\src\external\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\bombcrypto-bot-main-2\src\external\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - A operação foi concluída com êxito.

**Comment by newerton** [comment]
> max_accounts

Antes tinha um limitador que era esse max_accounts, agora estou contabilizando pelo total de contas no accounts.yaml

**Comment by newerton** [comment]
> Tentei intercalar aqui manualmente trocando para outra tela do bomb, deu o seguinte erro no bot:
> 
> 2022-04-19 11:21:02 - 🪟 Browser Active: Bombcrypto - Google Chrome Traceback (most recent call last): File "C:\bombcrypto-bot-main-2\index.py", line 51, in main() File "C:\bombcrypto-bot-main-2\index.py", line 37, in main multi_account.start() File "C:\bombcrypto-bot-main-2\src\multi_account.py", line 54, in start self.botMultiAccount() File "C:\bombcrypto-bot-main-2\src\multi_account.py", line 113, in botMultiAccount self.activeWindow(last, window) File "C:\bombcrypto-bot-main-2\src\multi_account.py", line 196, in activeWindow window.activate() File "C:\bombcrypto-bot-main-2\src\external\pygetwindow_pygetwindow_win.py", line 246, in activate _raiseWithLastError() File "C:\bombcrypto-bot-main-2\src\external\pygetwindow_pygetwindow_win.py", line 99, in _raiseWithLastError raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode))) pygetwindow.PyGetWindowException: Error code from Windows: 0 - A operação foi concluída com êxito.

Com quantas contas você está usando o bot?

**Comment by LeandroBraccio** [comment]
Duas contas.

**Comment by LeandroBraccio** [comment]
Eu teria que deixar assim entao?

1: { username: "", password: "", house: false, rarity: [] }
2: { username: "", password: "", house: false, rarity: [] }

**Comment by LeandroBraccio** [comment]
Testei aqui...agora está intercalando entre as duas contas. Na primeira fez certinho, colocou para trabalhar, foi pro mapa e trocou para a segunda conta. Na segunda conta, ele foi pra pagina de herois, não clicou em nenhum Work, só rolou a pagina e saiu. Que estranho

**Comment by newerton** [comment]
> Eu teria que deixar assim entao?
> 
> 1: { username: "", password: "", house: false, rarity: [] } 2: { username: "", password: "", house: false, rarity: [] }

Você não está uasndo contas com usuário e senha? Recomendo usar sempre usuário e senha, pela segurança da metamask.

**Comment by LeandroBraccio** [comment]
Segui essa sua dica, configurei usuario e senha para as duas contas. Agora está rodando tudo perfeitamente. Obrigado @newerton pela ajuda. Muito sucesso pra ti man!
