### ISSUE TITLE
[SUGESTÃO] Comando PAUSE e STOP

### ISSUE THREAD

**Issue by badnewsdev** [newerton/bombcrypto-bot#152]
1. Adicionar comando /pause no telegram, bot ficará pausado e irá retomar após 1 hora (reconhecendo erros/disconnect)
2. Adicionar comando /stop no telegram (CTRL+C in cmd)

Por qual motivo esses comandos?
R: Eu particularmente tenho uma escolinha, alguns dos meus clientes gostam de fazer o modo aventura, o comando /pause seria essencial para o cliente usufruir quando quiser.

**Comment by newerton** [comment]
Esses comandos afeta o multiaccout.

Se você pausar o jogo, o outro usuário acessar para jogar o modo aventura, a sua conta cai e vai para tela de login. Se esse registro for constante do usuário ficar jogando modo aventura, sem você sair da conta dele, essa conta vai ser banida.

E o comando stop em multiaccount vai parar todas as contas.
