### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by saad21212121** [newerton/bombcrypto-bot#157]
the bot is stop after 2 or 3 h  
Traceback (most recent call last):
  File "C:\lwai1\index.py", line 65, in <module>
    main()
  File "C:\lwai1\index.py", line 51, in main
    multi_account.start()
  File "C:\lwai1\src\multi_account.py", line 54, in start
    self.botMultiAccount()
  File "C:\lwai1\src\multi_account.py", line 113, in botMultiAccount
    self.activeWindow(last, window)
  File "C:\lwai1\src\multi_account.py", line 196, in activeWindow
    window.activate()
  File "C:\lwai1\src\external\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\lwai1\src\external\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - The operation completed successfully.

**Comment by saad21212121** [comment]
the coinfinf fele is ....
app:
  theme: "default"
  verify_version: true
  emoji: true
  terminal_colorful: true
  run_time_app: 1
  monitor_to_use: 1
  captcha: false
  speed: "fast"
  authenticate: true
  multi_account:
    enable: true
    window_title: "bombcrypto"
    window_fullscreen: false

time_intervals:
  send_heroes_for_work: [30, 35]
  refresh_heroes_positions: [3, 4]

chests:
  values:
    divide: 2
    chest_01: 0.01425
    chest_02: 0.03250
    chest_03: 0.16250
    chest_04: 0.32500

threshold:
  default: 0.7
  error_message: 0.7
  back_button: 0.9
  work_button: 0.9
  home_enable_button: 0.98
  heroes_green_bar: 0.9
  heroes_red_bar: 0.9
  heroes_full_bar: 0.9
  heroes_send_all: 0.9
  heroes_rest_all: 0.9
  chest: 0.65
  jail: 0.8
  auth_input: 0.9
  heroes:
    common: 0.8
    rare: 0.8
    super_rare: 0.8
    epic: 0.8
    legend: 0.8
    super_legend: 0.8

heroes:
  mode: "green"
  list:
    scroll_attempts: 3

offsets:
  work_button_green: [120, 140]
  work_button_full: [90, 110]
  house_button: [260, 280]

metamask:
  enable: false
  password: ""

services:
  telegram: true

log:
  save_to_file: false
  console: false
  show_print: false

**Comment by newerton** [comment]
What operating system are you using?

**Comment by saad21212121** [comment]
> What operating system are you using?

win 11

**Comment by saad21212121** [comment]
and i test it on win 10  its same proplem

**Comment by newerton** [comment]
How are you leaving the windows? maximized? minimized or side by side?

Not getting any windows on top of browsers? For example the terminal?

**Comment by saad21212121** [comment]
this is after 12 h work
