### ISSUE TITLE
Está funcionando com a versão mais nova do bomb?

### ISSUE THREAD

**Issue by jeffersonmdias** [newerton/bombcrypto-bot#159]
Está funcionando com a versão mais nova do bomb?
Estou tendo o seguinte erro:

```
Press Enter to start the bot...

2022-05-19 10:19:38 - Starting bot...
2022-05-19 10:19:41 - Terms and Service accepted in cache
2022-05-19 10:19:41 - Multi account enabled
Traceback (most recent call last):
  File "C:\Users\Bomb\Desktop\bombcrypto-bot-1.9.0\index.py", line 50, in <module>
    main()
  File "C:\Users\Bomb\Desktop\bombcrypto-bot-1.9.0\index.py", line 36, in main
    multi_account.start()
  File "C:\Users\Bomb\Desktop\bombcrypto-bot-1.9.0\src\multi_account.py", line 53, in start
    self.botMultiAccount()
  File "C:\Users\Bomb\Desktop\bombcrypto-bot-1.9.0\src\multi_account.py", line 89, in botMultiAccount
    total_accounts = len(self.accounts)
TypeError: object of type 'NoneType' has no len()
Starting bot with infinite execution!
```

**Comment by newerton** [comment]
https://github.com/newerton/bombcrypto-bot/blob/main/docs/README_pt-br.md#auth-with-user-and-pass

**Comment by jeffersonmdias** [comment]
> https://github.com/newerton/bombcrypto-bot/blob/main/docs/README_pt-br.md#auth-with-user-and-pass

acho que não entendi, no caso eu ja criei os usuários do jeito que ta orientando, e apaguei a parte example- na config e account.

**Comment by newerton** [comment]
O erro é no accounts.yaml, ele não encontrou esse arquivo.

**Comment by jeffersonmdias** [comment]
> O erro é no accounts.yaml, ele não encontrou esse arquivo.

o que eu faço para resolver? 
![image](https://user-images.githubusercontent.com/58378874/169316138-e4d8eb4d-8488-4b4d-bb3f-3667949053de.png)

**Comment by jeffersonmdias** [comment]
![image](https://user-images.githubusercontent.com/58378874/169316984-29e7ee01-c000-42c1-97e6-c9f8be24dcfc.png)
![Sem título](https://user-images.githubusercontent.com/58378874/169317747-d78af1f2-7229-42ae-b725-6156dc32d226.jpg)
tem algo errado na config?

**Comment by newerton** [comment]
authenticate muda para true

**Comment by jeffersonmdias** [comment]
> authenticate muda para true

consegui, eu peguei a versão mais atual sua, eu tava usando uma anterior e mudei o authenticate e foi, antes mesmo com o authenticate true não ia, obrigado pela ajuda.
