### ISSUE TITLE
Too many hero clicks, try to increase the back_button threshold

### ISSUE THREAD

**Issue by rodrigoomuller** [newerton/bombcrypto-bot#162]
Após a atualização de hoje o bot não está mais rolando a lista de herois e fica clicando sempre nos mesmos 2 herois ativos. Já tentei mudar threshold do work button e do back button e não adiantou.

**Comment by rodrigoomuller** [comment]
Alguma novidade sobre esse issue? Diminuiu bastante o farm depois desse bug.

**Comment by Bizukw** [comment]
Da uma olhada na issue já resolvida. #163

**Comment by newerton** [comment]
@Bizukw Obrigado! :*

**Comment by newerton** [comment]
Foi alterado a cor do fundo do botão WORK, com o threshold => work_button 0.90 o bot estava achando semelhança nos botões. Altera para 0.95.
