### ISSUE TITLE
Too many hero clicks

### ISSUE THREAD

**Issue by RoyalMagmaa** [newerton/bombcrypto-bot#163]
the bots click on the same heroes and even those who are already working since the update

**Comment by newerton** [comment]
@RoyalMagmaa Change threshold => work_button to 0.95

**Comment by RoyalMagmaa** [comment]
Thanks you bro and i was wondering if the bot would be compatible to handle normal mod and amazon mod

**Comment by newerton** [comment]
It's under development, there will be an option in config.yaml to select game mode.

**Comment by RoyalMagmaa** [comment]
okay niquel, the best would be for the bits to manage the 2 modes at the same time because the same heroes are not working.  Like an option other than houses in account -houses [], amazon: false or true

**Comment by newerton** [comment]
It can't be at the same time, when you leave survival mode and go to hunt mode, you stop farming in survival mode. It is not possible to play both modes.

**Comment by RoyalMagmaa** [comment]
okay my bad, but then for scholars make an option in account for amazon or the other mode

**Comment by RoyalMagmaa** [comment]
Hello i have the same problem with the new update but this issues doesn't work

**Comment by newerton** [comment]
@RoyalMagmaa Get last version and adjust the threshold and offsets.

https://github.com/newerton/bombcrypto-bot/issues/174#issue-1258288364

**Comment by RoyalMagmaa** [comment]
Yeah I have take the last version and I put the work but it doesn't work_button to 0.95 the bot does not recognize the heroes to put to work

**Comment by newerton** [comment]
Enable show_print, and adjust the threshold.

Enable show_print, and check if the printscreen that the bot will show you is appearing with a red outline or border.

Example: https://github.com/newerton/bombcrypto-bot/issues/174#issuecomment-1145475429

**Comment by RoyalMagmaa** [comment]
it just gives me a screenshot I don't see how to adjust and i don't see red outline

**Comment by newerton** [comment]
You adjust the threshold in config.yaml, change the heroes_green_bar to 0.85 and restart the bot.

Will test with other values.

**Comment by RoyalMagmaa** [comment]
Same the bit don't detect the work button

**Comment by RoyalMagmaa** [comment]
my settings worked on 1.9.7 I have a 1280/720p screen and I use Fullscreen mode

**Comment by newerton** [comment]
If you clicked the game's blue fullscreen button, it will never work.

**Comment by RoyalMagmaa** [comment]
no i just put the page in f11 and it worked with the aversion 1.9.7 bot with the work button at 0.95. but since the update the bot doesn't recognize the work button anymore it says there is no hero to send

**Comment by newerton** [comment]
Change work_button to 0.7 and heroes_green_bar to 0.7

**Comment by RoyalMagmaa** [comment]
now the bot recognizes but click on the left button so it does not send the heroes

**Comment by RoyalMagmaa** [comment]
I do not see how to make the bot click more to the right on the work buttom because it clicks on the bor of the green bar on the left

**Comment by newerton** [comment]
https://github.com/newerton/bombcrypto-bot/issues/163#issuecomment-1146138658

**Comment by RoyalMagmaa** [comment]
thanks this work this heroes_green_bar to 0.7

**Comment by RoyalMagmaa** [comment]
![P_20220619_154955](https://user-images.githubusercontent.com/106256283/174484491-6abef9d4-8d2c-4353-ad27-dbdbc04d1e90.jpg)
hello, here I am again the bots crash every day with this error.  hoping you can help me

**Comment by newerton** [comment]
@RoyalMagmaa Set verify_version to false.

**Comment by RoyalMagmaa** [comment]
Hello, since the update of bolbcrypto when the bots try to identify themselves with the identifiers, the screen shifts a little bit, and suddenly when he clicks to put the password he clicks a little too high  and it is not taken into account ducoup, I do not know that they value to modify
