### ISSUE TITLE
usar no modo amazon

### ISSUE THREAD

**Issue by Brian-bq** [newerton/bombcrypto-bot#164]
tem como colocar para usar o modo amazon?

**Comment by Bizukw** [comment]
![treasure_hunt_banner](https://user-images.githubusercontent.com/105728771/170863957-ebc78173-2d24-4ab3-b036-3d334d6d83a2.png)
Substitui

**Comment by Brian-bq** [comment]
Obrigado

**Comment by HikeThy** [comment]
Mas ai o bot so faz o modo amazon ne?

**Comment by newerton** [comment]
@HikeThy Não tem como fazer os dois ao mesmo tempo.

**Comment by newerton** [comment]
Bot atualizado, agora tem o modo amazon survival.
