### ISSUE TITLE
Meu bot esta bugando em alguns casos

### ISSUE THREAD

**Issue by Brian-bq** [newerton/bombcrypto-bot#165]
1: Esté clicando varias vezes nos primeiros heroes pra enviar pra trabalhar e geralmente n esta clicando nos ultimos da lista
2: não esta enviando os heroes para casa

**Comment by newerton** [comment]
@Brian-bq muda o threshold dos botões. Ultimas atualizações, os dev mudaram a cor dos botões. Coloca o botão de WORK para 0.95
