### ISSUE TITLE
Dúvida sobre outro bot seu

### ISSUE THREAD

**Issue by jeffersonmdias** [newerton/bombcrypto-bot#166]
O bot do sunflower land ta funcionando?
Estou peguntando aqui porque lã não tem a opção.

**Comment by newerton** [comment]
@legnatv To com receio de publicar os arquivos, por que eles colocaram alguns script anti-bot no código. Mas não detecta meu bot, por que é auto-click. Já testei ele bastante, até aquela parte chata de buscar o Goblin com a pá está pronto.

**Comment by legnatv** [comment]
Posso ter acesso a ele? 😀

**Comment by jeffersonmdias** [comment]
> @legnatv To com receio de publicar os arquivos, por que eles colocaram alguns script anti-bot no código. Mas não detecta meu bot, por que é auto-click. Já testei ele bastante, até aquela parte chata de buscar o Goblin com a pá está pronto.

Posso ter acesso a essa versão funcionando ou é essa mesma que está disponível?
