### ISSUE TITLE
Conectar-se pelo login

### ISSUE THREAD

**Issue by megamandev** [newerton/bombcrypto-bot#169]
1: { username: "", password: ""

preciso colocar aqui meu username e password ?
porque no meu caso já está salvo no navegador.
ainda assim há necessidade de colocar ?

muito obrigado por disponibilizar esse bot, abraço!

**Comment by megamandev** [comment]
meu username e password já estão salvos no navegador, quando eu abro o bomb já esta lá preenchido o meu username e pass
queria que o bot apenas clica-se no botão de login pra iniciar o game
pelo o que eu entendi o bot que inserta o username e pass, correto ?
onde posso alterar para o bot apenas clikar no botao login ?

**Comment by newerton** [comment]
> 1: { username: "", password: ""
> 
> preciso colocar aqui meu username e password ? porque no meu caso já está salvo no navegador. ainda assim há necessidade de colocar ?
> 
> muito obrigado por disponibilizar esse bot, abraço!

O bot funciona em single account e multi account. Não tem como deixar no meio termo. E tem usuários que usa o bot para escolinhas, e eles usam 1 conta só para várias escolinhas. Imagina o usuário tem que ficar logando sempre e depois ativar o bot, ai fica inviável.

**Comment by newerton** [comment]
> meu username e password já estão salvos no navegador, quando eu abro o bomb já esta lá preenchido o meu username e pass queria que o bot apenas clica-se no botão de login pra iniciar o game pelo o que eu entendi o bot que inserta o username e pass, correto ? onde posso alterar para o bot apenas clikar no botao login ?

Você pode editar o auth.py

**Comment by megamandev** [comment]
@newerton 

tem razão em relação a escolinha
obrigado man, tenho um bot que coloca os herois para trabalhar pela % de stamina de 0 a 100% ae vc define quanto vc quer no arquivo conf.
mas esse bot nao colocar pra descansar na casa
consegue implementar casa nesse bot, é um bot muito bom pena que nao tem opcao de enviar pra casa
