### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by megamandev** [newerton/bombcrypto-bot#170]
@newerton 

tenho um bot que envia os heróis para trabalhar de acordo com a porcentagem de estamina de 0 a 100%, definida no arquivo config.py

entretanto esse bot não tem a função de enviar para descansar na casa.
e também so faz login pelo metamask, mas isso nem preciso porque eu faço o login manualmente pelo login e senha,
depois que ta na tela do caça tesouro eu coloco o bot pra rodar com comando python3 main.py

mano pode me ajudar a implementar essa nova função
eu já tentei implementar editando os seguintes arquivos
config.py
image.py
bombscreen.py
manager.py

tirei print da image home checked e unchecked, coloquei na pasta targets
mas não funcionou =(

pode me ajudar a implementar isso no bot
obrigado mano.

**Comment by newerton** [comment]
@megamandev A parte de porcentagem de estamina meu bot não tem, do resto ele envia para a casa os heróis por raridade.

Por porcentagem não é dificil fazer, você vai precisar pegar um heroi comun com 50 de stamina, e tirar o print da stamina quando estiver em 25%, 50%, 75%, por que 100% é o modo "full" do bot.

Mas na minha opnião, não vejo vantagem enviar heróis pela porcentagem de stamina, você vai ganhar no máximo entre 3% a 5%, muito esforço para pouca recompensa.

**Comment by megamandev** [comment]
eu tenho um bot que já tem essa funcao, ele envia os herois pra trabalhar conforme vc define a porcentagen e raridade
no caso aqi eu botei pra enviar os super raro com 30% e comum com 60%
mas esse bot aqi nao envia pra casa.
to tentando implementar nele essa funcao casa mas nao to conseguindo.
vc pode ate usar essa funcao da porcentagen de estamina no sue bot se vc qiser.

se tiver tempo e puder me ajudar eu te envio o link do github do bot

obrigado por responder man. valeu

**Comment by newerton** [comment]
Para enviar para a casa é mais complexo, por que os heróis vai para o final da lista, mudando a posição dos próximos heróis, você vai precisa inverter a ordem dos cliques, ao invez de começar de cima para baixo, mudar para clicar de baixo para cima.

No meu bot já tem essa parte pronta.

Esta parte da porcentagem por enquanto não vou implementar, muito trabalho para pouca recompensa, se em um futuro sombrio essas moeda subir, ai eu implemento.
