### ISSUE TITLE
Meu bot esta apresentando alguns erros

### ISSUE THREAD

**Issue by Brian-bq** [newerton/bombcrypto-bot#177]
![Screenshot_10](https://user-images.githubusercontent.com/96246285/171734087-916908d6-2937-4b8e-9c78-efff0c4805ef.png)

**Comment by newerton** [comment]
@Brian-bq Qual versão está usando?

**Comment by newerton** [comment]
Pelo erro, você está executando o bot 2x na mesma maquina, e com o Telegram ativo nesses bots.

**Comment by Brian-bq** [comment]
Estou com apenas 1 bot na maquina, porem tem outro bot em uma outra maquina rodando tbm, mas usando o mesmo bot do telegram
isso gera problemas?

**Comment by newerton** [comment]
@Brian-bq Sim, por causa da conexão com o Telegram, o Telegram permite somente 1 conexão com o bot deles. Como está tendo 2 conexão, ou os 2 bots cai, ou somente o último conectado.
