### ISSUE TITLE
Multi account

### ISSUE THREAD

**Issue by Globtrotter85** [newerton/bombcrypto-bot#180]
Hello,

I configured the bot on my linux vps a few hours ago and it works very well. However, when I try to configure the multi-account, the software enlarges the window while the "fullscreen" variable is set to "false". Then, the software tries to change the account but it goes to the files instead of changing the tab (or the page...).

How to configure the multi-account and how to use it? I have to have several browsers open, or several tabs on Mozilla for example.

Thanks in advance!

**Comment by newerton** [comment]
Hi! Bot will work 1 account at a time. You can put the windows side by side, but the bot will maximize 1 at a time and perform the operations.

The bot only works for windows and not for tabs.
