### ISSUE TITLE
bot keep trying to login with metmask

### ISSUE THREAD

**Issue by selk92** [newerton/bombcrypto-bot#186]
Hello, I recently tried the bot, renamed the config file, checked it and even with the default config (metamask: false) it keep trying to log in with metamask, am I doing something wrong ? 

Here's my config file : 

app:
  theme: "default"
  game: 'amazon_survival' # 'treasure_hunt' or 'amazon_survival'
  verify_version: true
  emoji: false
  terminal_colorful: false
  run_time_app: 1
  monitor_to_use: 1
  captcha: false
  speed: "fast"
  authenticate: false
  multi_account:
    enable: false
    window_title: "bombcrypto"
    window_fullscreen: false

time_intervals:
  send_heroes_for_work: [30, 35]
  refresh_heroes_positions: [3, 4]

chests:
  values:
    divide: 2
    chest_01: 0.01425
    chest_02: 0.03250
    chest_03: 0.16250
    chest_04: 0.32500

threshold:
  default: 0.7
  error_message: 0.7
  back_button: 0.9
  work_button: 0.95
  home_enable_button: 0.95
  heroes_green_bar: 0.95
  heroes_red_bar: 0.98
  heroes_full_bar: 0.8
  heroes_send_all: 0.9
  heroes_rest_all: 0.9
  chest: 0.70
  jail: 0.8
  auth_input: 0.9
  heroes:
    common: 0.8
    rare: 0.8
    super_rare: 0.8
    epic: 0.8
    legend: 0.8
    super_legend: 0.8

heroes:
  mode: "green"
  list:
    scroll_attempts: 3

offsets:
  work_button_green: [160, 190]
  work_button_full: [90, 120]
  house_button: [280, 310]

metamask:
  enable: false
  password: ""

services:
  telegram: false

log:
  save_to_file: false
  console: false
  show_print: false

**Comment by newerton** [comment]
authenticate: true

**Comment by selk92** [comment]
Perfect thank you for this insanely fast reply :)
