### ISSUE TITLE
Adicionar a nova versão no releases

### ISSUE THREAD

**Issue by Raoniq** [newerton/bombcrypto-bot#187]
Bom dia, será que é possível adicionar a versão mais atual (2.0.5) no releases ? Tentei atualizar usando o update_files.bat mas não consegui de jeito nenhum.

**Comment by newerton** [comment]
@downloadkct Para usar o update_files.bat, você precisa instalar o git no seu sistema operacional.

**Comment by Raoniq** [comment]
> @downloadkct Para usar o update_files.bat, você precisa instalar o git no seu sistema operacional.

Pior que eu instalei, mas ele diz que não consegue encontrar o caminho do requirements

**Comment by newerton** [comment]
Você tem que executar o update_files,bat, fora da pasta cmd,

```shell
.\cmd\update_files.bat
```

**Comment by Raoniq** [comment]
> Você tem que executar o update_files,bat, fora da pasta cmd,
> 
> ```shell
> .\cmd\update_files.bat
> ```

Já fiz mas dá o erro da imagem, eu dentro do git cmd e diz que não tenho o git instalado o.o
![1](https://user-images.githubusercontent.com/24975841/172459588-33ac63e8-f22c-4420-94f5-736d445b0d92.jpg)

**Comment by newerton** [comment]
@downloadkct Se você já instalou o git for windows.

Vai dentro da pasta C:\Users\Bomb\Desktop\

E digita esse comando aqui:
```
git clone https://github.com/newerton/bombcrypto-bot.git
```

Esse comando vai fazer o clone do projeto do bomb, é a mesma coisa que fazer download. Deste modo de clone, você mantem mais atualizado os arquivos.

Para esse erro que está dando de git, e por que o modulo do git foi removido do requeriments.txt do python, mas você pode instalar com esse comando aqui:

```
pip install GitPython
```
