### ISSUE TITLE
Boa noite, teria algum video ensinando configurar o bot?

### ISSUE THREAD

**Issue by LucasMendes25** [newerton/bombcrypto-bot#188]
instalei tudo certo, porem não consigo configurar ele, se alguém puder fazer um vídeo ensinando eu agradeço muito

**Comment by newerton** [comment]
@LucasMendes25 Esse é o único bot mais fácil de configurar.

https://github.com/newerton/bombcrypto-bot/blob/main/docs/README_pt-br.md

Você só precisa adicionar suas contas no accounts.yaml, ativar o authenticate: true dentro do config.yaml e só.

**Comment by LucasMendes25** [comment]
> @LucasMendes25 Esse é o único bot mais fácil de configurar.
> 
> https://github.com/newerton/bombcrypto-bot/blob/main/docs/README_pt-br.md
> 
> Você só precisa adicionar suas contas no accounts.yaml, ativar o authenticate: true dentro do config.yaml e só.

ele fica mudando o tamanho da tela, tipo clicando no botão onde deixa a tela em janela e maximizada
