### ISSUE TITLE
bot dando duplo clique na barra do navegador 

### ISSUE THREAD

**Issue by LucasMendes25** [newerton/bombcrypto-bot#189]
Fiz toda a instalação/configuração, ele inicia, coloca os heroes para trabalhar porem depois disso ele fica dando duplo clique na barrado do navegador (alternando modo janela) no processo "browser active" alguém sabe me dizer como conserto? desde ja agradeço a atenção

**Comment by LucasMendes25** [comment]
consegui arrumar, passando a opção "window_fullscreen" para "true" alguem sabe me dizer qual intervalo de tempo para alternar de uma conta para outra?

**Comment by newerton** [comment]
@LucasMendes25 É automático, se um navegador não está no tempo de execução de nenhuma tarefa, o bot vai para o próximo navegador.
