### ISSUE TITLE
Metabomb

### ISSUE THREAD

**Issue by leonardo3dp** [newerton/bombcrypto-bot#191]
Saiu o [metabomb](https://metabomb.io/) parecido com bomb sera que rola um bot?

**Comment by newerton** [comment]
@leonardo3dp Estou analisando aqui, não sei se é por causa do hyper, mas os herois está um pouco caro, esperar esse hyper baixar. Tem um video de um vietnamita jogando, ele tem 3 raro e 1 comun em 2 mapas ele ja fez 515 MTB.

Me parece um bom jogo com boas recompensas. Mas pelo vídeo está fácil de fazer o bot, mas inicialmente vou precisar de uma conta com herois ou esperar baixar um pouco esses preços.

**Comment by newerton** [comment]
https://github.com/newerton/metabomb-bot/

Para quem quiser fazer doação, preciso de 7000 MTB para comprar um heroi comum. Ai inicio o desenvolvimento do bot.

MTB: 0x4847C29561B6682154E25c334E12d156e19F613a
