### ISSUE TITLE
Bot não alterna contas (mult-account)

### ISSUE THREAD

**Issue by LucasMendes25** [newerton/bombcrypto-bot#192]
Boa tarde, tudo bem? meu bot não esta alternando entre as contas, roda normalmente porem ficou por 1 hora rodando em apenas uma das contas, na configuração esta tudo configurado, alguém pode me ajudar?

**Comment by newerton** [comment]
@LucasMendes25 A outra conta não foi desconectada ou algum erro deu na outra conta?
