### ISSUE TITLE
Contas desconectando com frequencia

### ISSUE THREAD

**Issue by igorangelice** [newerton/bombcrypto-bot#193]
O problema: as contas desconectam com muita frequencia,.

Estou usando no Ubuntu o bot, rodo 2x maquinas virtuais com 2 processadores e 2gb de ram, com resolução 1366x768. Primeiro eu tentei usando o multi contas, em uma máquina só com 4 nucleos e 4gb de ram, só que ficava alternando a tela com pouquissimos segundos de diferença. Achei que pudesse ser isso, por isso quebrei essa maquina em duas e deixei de usar o multiacc. Não adiantou.

Sabe se pode ser alguma configuração?

**Comment by newerton** [comment]
@igorangelice Se está usando multiaccount, tem que mudar o refresh_heroes_positions para [1,1] que é 1 minuto.

Se você colocar mais, você pode ser desconectado. Por que a ação de colocar os heróis na lista, já demora mais de 1 minuto se houver muito heróis para enviar para o mapa.

E quando o bot voltar para o outro navegador, ele vai fazer a atualização no mapa, e depois vai mudar de navegador. Começa com 1 minuto, depois muda para 2 minutos.

**Comment by igorangelice** [comment]
Boa, valeu pela resposta rapida! Vou tentar aqui, abs.
