### ISSUE TITLE
Farm in different modes

### ISSUE THREAD

**Issue by johndavemanuel** [newerton/bombcrypto-bot#194]
Is it possible to run in multi accounts but accounts are farming in tresure hunt and Amazon ?

**Comment by newerton** [comment]
No, a user already commented on this. I will implement this this week.

**Comment by johndavemanuel** [comment]
cool. will wait for that. 🎉

**Comment by newerton** [comment]
@johndavemanuel Update the bot! 2.0.6

**Comment by johndavemanuel** [comment]
@newerton nice, the readme.md needs to be updated
