### ISSUE TITLE
Time intervals

### ISSUE THREAD

**Issue by selk92** [newerton/bombcrypto-bot#196]
Hello,

I'm trying to optimize the bot's settings but I don't understand how works these lines : 

time_intervals 
-- | -- | --
send_heroes_for_work | array - [int, int] | Start and end time for bot to search for heroes to work
refresh_heroes_positions | array - [int, int] | Start and end interval for bot to update map

Can you explain me with an example how start and end times works please ?

**Comment by newerton** [comment]
@selk92 Hello,

The send_heroes_for_work and the refresh_heroes_positions , works with minutes. These values are a range of minutes.

Example:
send_heroes_for_work: [10,20]

The send_heroes_for_work function will run between 10 to 20 minutes. The bot will fetch a random value from 10 to 20 minutes.

**Comment by selk92** [comment]
Perfect, I understood, thanks ;)
