### ISSUE TITLE
Amazon mode não manda heróis 

### ISSUE THREAD

**Issue by Raoniq** [newerton/bombcrypto-bot#199]
Boa tarde, estou tentando usar no modo Amazon mas não funciona. Nem o modo "green" e nem o modo "all" funcionam.
Eu verifiquei a imagem e tentei diminuir o Threshold mas não funcionou, ele trava na tela abaixo e não clica em 'all', depois de um tempo ele simplesmente fecha a tela dos heróis e volta pro modo amazon sem ter enviado heróis.
![1](https://user-images.githubusercontent.com/24975841/172933241-7c37b979-5d47-4e5f-8180-e5a42d564634.jpg)

**Comment by newerton** [comment]
@downloadkct Você ajustou o threshold com essas config aqui: https://github.com/newerton/bombcrypto-bot/issues/174

**Comment by Raoniq** [comment]
> @downloadkct Você ajustou o threshold com essas config aqui: #174
Sim, e depois fui baixando conforme a instrução nesse comentário, mas nada acontece.

![image](https://user-images.githubusercontent.com/24975841/172940813-8de562a4-9dc4-41c6-afda-47b857a4ae0d.png)

**Comment by newerton** [comment]
Coloca no heroes_green_bar 0.7, e muda o heroes mode para green
