### ISSUE TITLE
Scholar TH & Amzon

### ISSUE THREAD

**Issue by RoyalMagmaa** [newerton/bombcrypto-bot#202]
Hello,
thank you for your bot which is already amazing,
I wanted to know if it is possible to manage simultaneously accounts in TH and another in Amazon.
If it is not, is it planned? 

Thanks in advance

**Comment by newerton** [comment]
@RoyalMagmaa Configure in the accounts.yaml

https://github.com/newerton/bombcrypto-bot/blob/main/config/EXAMPLE-accounts.yaml

**Comment by RoyalMagmaa** [comment]
thanks you so much for your reactivity and your job

**Comment by RoyalMagmaa** [comment]
hello I have a new problem that I had not seen, the bot sends the heroes to work but does not take into account their stamina so they send all the heroes who should be at rest. I don't know what values I should use.

**Comment by newerton** [comment]
@RoyalMagmaa Use this config: https://github.com/newerton/bombcrypto-bot/issues/174#issue-1258288364

**Comment by RoyalMagmaa** [comment]
I use it but it was not working I had to put the heroes_green_bar: 0.7 for the bot to detect the heroes

**Comment by RoyalMagmaa** [comment]
good thanks sorry
