### ISSUE TITLE
versão 2.0.7

### ISSUE THREAD

**Issue by Raoniq** [newerton/bombcrypto-bot#204]
Boa noite! Obrigado pelo bot, após algumas modificações eu consegui fazer funcionar no modo "all" no amazon mode.
A minha dúvida é, o que tem de novo na versão 2.0.7 ?

**Comment by newerton** [comment]
@downloadkct Por mais que você desativa a opção de não verificar os updates, o bot estava verificando o arquivo de versão a cada loop. Com isso as vezes o bot dava crash, por que causa de alguns timeout com a url do GitHub.

Agora não vai mais acontecer isso, se você deixar o verify_version: false
