### ISSUE TITLE
When authenticating the bots click a little too high and therefore the hitbox of the box does not take it into account

### ISSUE THREAD

**Issue by RoyalMagmaa** [newerton/bombcrypto-bot#207]
![image](https://user-images.githubusercontent.com/106256283/175250082-65daebdf-e3cf-4745-9553-b4499907f3a8.png)
Hello, since the update of bolbcrypto when the bots try to identify themselves with the identifiers, the screen shifts a little bit, and suddenly when he clicks to put the password he clicks a little too high and it is not taken into account ducoup, I do not know that they value to modify

**Comment by RoyalMagmaa** [comment]
you can't see the cursor on the first screen
![image](https://user-images.githubusercontent.com/106256283/175250665-a2c00686-1b95-45cb-a622-acc389b54061.png)
I represented it in red

**Comment by newerton** [comment]
@RoyalMagmaa Is the red line the position of the username or password?
The game didn't change the image, but I can give you the line for you to change and test.

**Comment by RoyalMagmaa** [comment]
Is the line password

**Comment by newerton** [comment]
@RoyalMagmaa Change this file: https://github.com/newerton/bombcrypto-bot/blob/main/src/auth.py#L69

Before:
```
self.actions.move((int(x+100), int(y+10)), 1)
```

After:
```
self.actions.move((int(x+100), int(y+15)), 1)
```

**Comment by RoyalMagmaa** [comment]
Thx I will try that

**Comment by RoyalMagmaa** [comment]
Okay thanks I had to put 20 for it to work, however I had new accounts (nothing to see) in the meantime with houses, I put like this:

1: {
    mode: "amazon_survival", # 'treasure_hunt' or 'amazon_survival
    username: "xxxx",
    password: "xxx",
    house: true,
    rarity: ["rare", "super_rare", "epic", "legend", "super_legend"],
  }

and the bots don't use it, maybe because of the rarity I didn't understand very well what it was (in my account most of them are full super_rare).

Translated with www.DeepL.com

**Comment by RoyalMagmaa** [comment]
sorry to raise did you see?

**Comment by newerton** [comment]
Fixed
