### ISSUE TITLE
O meu bot para de funcionar e voltar para o inicio pedindo para apertar enter

### ISSUE THREAD

**Issue by jeffersonmdias** [newerton/bombcrypto-bot#208]
Boa noite,
Estou enfrentando um problema, meu bot coloca 3 contas para farmar certinho, mas ao fazer isso ele volta para aquela parte inicial que pede para apertar enter para iniciar o bot.
tenho 6 contas e os arquivos de login estão certinho e modo amazon.
Editei apenas o authenticate para true e coloquei para modo All .
O resto nao editei nada.

Sabe me orientar?

**Comment by Raoniq** [comment]
Aqui está acontecendo isso tb :(

**Comment by newerton** [comment]
@legnatv @downloadkct Está usando o comando python index.py ou o start.bat/start.sh ?

**Comment by jeffersonmdias** [comment]
> @legnatv @downloadkct Está usando o comando python index.py ou o start.bat/start.sh ?

eu estou usando o start.bat, ele tinha voltado a funcionar, mas de ontem para hoje voltou a parar.

**Comment by jeffersonmdias** [comment]
![image](https://user-images.githubusercontent.com/58378874/177005478-8b980a1a-6817-4842-b95e-896ed6dfd184.png)
@newerton este é o erro que ta dando e parando de funcionar..
