### ISSUE TITLE
Problema com Casa

### ISSUE THREAD

**Issue by cBassc** [newerton/bombcrypto-bot#211]
Boa tarde,

e já adianto obrigado pelo bot, maravilhoso.
----------------------------------------------------

Uso numa VM Ubuntu da Oracle.

O problema:

Mais ou menos a cada 1h30 o bot mostra essa janela:
![House](https://user-images.githubusercontent.com/106779268/178792245-7c6e8960-6ffe-4d0d-8d91-a9dc76b1f88a.JPG)

E então o bot não consegue sair daí, qdo eu olho só clico no X vermelho e ele volta a funcionar.

Aí eu fui tentar usar o SHOW PRINT e só mostra o STARTING BOT e trava:
![Detected](https://user-images.githubusercontent.com/106779268/178793015-c2f2012a-1276-40fa-859a-7a2f00cfc334.JPG)

Daí qdo clico no X ali no canto direito em cima pra fechar a janela do DETECTED destrava, mas o bot continua travado, só abrindo outra aba do terminal pra usar de novo o bot.
Então desisti de mexer no SHOW PRINT.

A imagem abaixo foi tirada logo depois de uma travada da janela que diz BUY HOUSE:
![Python](https://user-images.githubusercontent.com/106779268/178795923-5defd6b7-3ed0-4f68-b1f3-83af0324df70.JPG)

E essa é de como estavam os personagens na hora que o bot tentava por na casa:
![Barra](https://user-images.githubusercontent.com/106779268/178794411-07930bdc-851d-4e21-8114-a819b42f0f71.JPG)

Pelo que entendi ele tentava por na casa quem estava fora, e quando a casa já está cheia e por algum motivo o jogo reconhece que não tem casa.

Uma forma fácil que pensei pra resolver isso é clicar no X vermelho pra fechar essa janela quando aparecer.
Só que não sei como programar isso.

Fico grato se puder ajudar :)
Obrigado.

**Comment by newerton** [comment]
@cBassc Eu tinha identificadao esse erro antes, mas não sei por que o jogo voltou com esse erro, por que se sua casa tem 4 espaços, o jogo antes não habilitava o botão de HOME (Marrom Claro), quando o bot selecionava 4 heróis o jogo mudava o botão de HOME para Cinza, igual ao print que você me mandou. Me parece que os dev voltou esse problema novamente.

Como eu não tenho conta com casa, só me tira uma dúvida, retira todos os heróis da casa, e inicia o bot.

E fica observando se o botão de HOME, muda para cinza, depois de enviar os heróis para casa.

**Comment by cBassc** [comment]
@newerton o botão HOME fica sim cinza logo depois da casa encher.

Eu queria muito ver o SHOW PRINT, mas como não roda não consigo entender pq ele chama esse erro de que não tem casa, só acho mesmo.
