### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by arnaldoojunior** [newerton/bombcrypto-bot#213]
Olá, estou com problema no momento do usuário e senha, o bot insere o usuário, mas não muda para o campo de baixo para inserir a senha, notei que ao invés disso o cursor volta algumas letras e o bot insere a senha no campo usuário, fazendo com que haja erro.
Existe alguma forma de resolver este problema?

p.s. Estou usando o bot no Ubuntu.

**Comment by newerton** [comment]
@arnaldoojunior Nova versão atualiza esse problema.
