### ISSUE TITLE
Bot not enter the password

### ISSUE THREAD

**Issue by easly113** [newerton/bombcrypto-bot#217]
I just found out the bot doesn't entering the password and its only entering the Username then click straight to login button.

**Comment by newerton** [comment]
What operating system are you using?

I just took this test
![login-bombcrypto](https://user-images.githubusercontent.com/4175945/180348587-bad8d19a-eb1f-436e-9dde-7b8007f8c2cc.gif)

**Comment by easly113** [comment]
> What operating system are you using?
> 
> I just took this test ![login-bombcrypto](https://user-images.githubusercontent.com/4175945/180348587-bad8d19a-eb1f-436e-9dde-7b8007f8c2cc.gif)

Well after i reset my Laptop, using cmd to open it again and now it works normally. Weird but ok, lol. Thanks anyway.
