### ISSUE TITLE
Bot não digita o login

### ISSUE THREAD

**Issue by LucasMendes25** [newerton/bombcrypto-bot#218]
Bom dia, tudo jóia ? Meu bot está funcionando perfeitamente, porém na tela de login ele não digita, alguém pode me ajudar ? Desde já agradeço a atenção

**Comment by LucasMendes25** [comment]
Conseguir arrumar, porém não consegui fechar essa

**Comment by newerton** [comment]
@LucasMendes25 Como arrumou? Vou ver se é problema aqui.
