### ISSUE TITLE
Ajuda com Telegram

### ISSUE THREAD

**Issue by jesusjogou** [newerton/bombcrypto-bot#219]
Alguém poderia me dar uma luz?
Não entendo nada sobre o bot ou python ou qualquer outra coisa que foi utilizada pra criação do bot, porém fuçando consigo me virar e arrumar alguns detalhes que as vezes travam os bots, porém nem imagino como fazer a integração com o Telegram.
Também não utilizava o app, sempre fui do whatsapp, isso pode estar atrapalhando um pouco também.

Achei o arquivo EXAMPLE-telegram.yaml na pasta, porém nem imagino o que devo fazer. 
O arquivo está dessa forma:
1 chat_ids: ["YOUR_CHAT_ID_1", "YOUR_CHAT_ID_2"]
2 botfather_token: "YOUR_BOTFATHER_TOKEN"
3 enable_coin_report: true
4 enable_map_report: true
5 format_of_image: "jpg"
6 enable_emergency_call: false

Também não fiz nada no Telegram.
Se puderem ajudar, agradeço...

**Comment by newerton** [comment]
@jesusjogou Tranquilo por ae?

Primeiramente você precisa criar um bot para o seu telegram.

Envia uma comando /help para o bot: https://t.me/BotFather

Ele vai listar esses comandos:
```
I can help you create and manage Telegram bots. If you're new to the Bot API, please see the manual (https://core.telegram.org/bots).

You can control me by sending these commands:

/newbot - create a new bot
/mybots - edit your bots [beta]

Edit Bots
/setname - change a bot's name
/setdescription - change bot description
/setabouttext - change bot about info
/setuserpic - change bot profile photo
/setcommands - change the list of commands
/deletebot - delete a bot

Bot Settings
/token - generate authorization token
/revoke - revoke bot access token
/setinline - toggle inline mode (https://core.telegram.org/bots/inline)
/setinlinegeo - toggle inline location requests (https://core.telegram.org/bots/inline#location-based-results)
/setinlinefeedback - change inline feedback (https://core.telegram.org/bots/inline#collecting-feedback) settings
/setjoingroups - can your bot be added to groups?
/setprivacy - toggle privacy mode (https://core.telegram.org/bots#privacy-mode) in groups

Games
/mygames - edit your games (https://core.telegram.org/bots/games) [beta]
/newgame - create a new game (https://core.telegram.org/bots/games)
/listgames - get a list of your games
/editgame - edit a game
/deletegame - delete an existing game
```

O que você vai precisar é o "create a new bot" e depois o comando /token.
O bot vai gerar um token para você (não compartilha), esse token você vai colocar no YOUR_BOTFATHER_TOKEN.

E para pegar o seu CHAT_ID, você envia uma mensagem com o comando /start para esse bot: https://t.me/userinfobot
Ele vai mostrar um ID, ai você coloca em YOUR_CHAT_ID_1, e pode apagar o YOUR_CHAT_ID_2.

**Comment by jesusjogou** [comment]
@newerton, cara, nem acredito. Muito obrigado. 
Não esperava uma resposta sua para algo que parece ser tão besta, quanto mais uma resposta rápida assim. Assim que farmar um tanto, não esquecerei do seu café.
Excelente bot e suporte que tu dá... Valeu demais.

**Comment by newerton** [comment]
@jesusjogou Obrigado e Amém! Vou lembrar que Jesus usou meu bot! hehe

Qualquer dúvida cria outra issue, vou fechar essa. Mas você pode voltar a responder nesta Issue mesmo que esteja fechada.
