### ISSUE TITLE
como selecionar o modo amazon survival?

### ISSUE THREAD

**Issue by thiagokazuza** [newerton/bombcrypto-bot#223]
bom, o título é autoexplicativo... meu bot só seleciona o treasure hunt... queria saber como fazer pra selecionar o amazon
também queria saber se está funcionando a opção de mandar pra home
obrigado

**Comment by newerton** [comment]
@thiagokazuza Lê a documentação: https://github.com/newerton/bombcrypto-bot/blob/main/docs/README_pt-br.md

![image](https://user-images.githubusercontent.com/4175945/187013518-1903dfb0-9aaa-4eed-b914-f014fd059a56.png)

![image](https://user-images.githubusercontent.com/4175945/187013496-dcf3e5f0-1e6d-4f1a-8e07-0bdd3ac3889c.png)
