### ISSUE TITLE
Problema com login versão 62

### ISSUE THREAD

**Issue by LucasMendes25** [newerton/bombcrypto-bot#225]
Boa tarde, tudo bem? alguém sabe como resolver o problema com o login na versão 62? ele loga porém tem uma tela nova antes da tela principal e ele fica atualizando a pagina, desde já agradeço a atenção.

**Comment by newerton** [comment]
@LucasMendes25 Fiz uma atualização agora, foi alterado 2 arquivos.

src/application.py
src/auth.py

**Comment by arnaldoojunior** [comment]
@newerton Tem como atualizar diretamente no jogo? Este "sh" não existe "./cmd/update_files.sh".
Ou para atualizar preciso baixar o arquivo zipado novamente?

**Comment by newerton** [comment]
@arnaldoojunior Se você tiver o git instalado, é só executar o gil pull n pasta do projeto, senão vai ter que baixar o zip novamente.

**Comment by arnaldoojunior** [comment]
@newerton, atualizei os 2 arquivos e continua sem fechar o anúncio.
