### ISSUE TITLE
Versão 63

### ISSUE THREAD

**Issue by arnaldoojunior** [newerton/bombcrypto-bot#231]
O bot não clica no modo Amazon, já substitui a imagem.

**Comment by newerton** [comment]
É por que removeram o treasure hunt do jogo, que bosta ta ficando esse jogo! Agora só tem o modo amazon, com certeza eles vão nerfa esse modo amazon de 200%~600% para 100%~200%.

Vou ter que alterar a imagem de espera.

**Comment by newerton** [comment]
Fiz atualização no bot.
