### ISSUE TITLE
conectar carteira

### ISSUE THREAD

**Issue by thiagokazuza** [newerton/bombcrypto-bot#232]
boa noite
meu bot não passa dessa parte
ele não clica na carteira da metamask pra conectar...
como eu resolvo?
desculpa se já tem algum tópico sobre isso, mas eu não consegui achar
obrigado desde já

![image](https://user-images.githubusercontent.com/110304770/192425065-1a1d1954-3df3-4ad5-bed8-6fe28988cf44.png)

**Comment by newerton** [comment]
@thiagokazuza Alterar para fazer o login com username e password.

Aqui mostsra como faz: https://github.com/newerton/bombcrypto-bot/blob/main/docs/README_pt-br.md

**Comment by thiagokazuza** [comment]
valeu!!
