### ISSUE TITLE
fix: bot command bug

### ISSUE THREAD

**Issue by agsfmlcx** [newerton/bombcrypto-bot#32]
When a robot sends a .bcoin command, the obtained image is not real-time but cached after the last newmap. This is not consistent with the performance of versions before 1.5.2, including the .map command.

**Comment by newerton** [comment]
@agsfmlcx Thanks for the feedback, the getBcoin() function is fetching the generated image after the map estimate. The /bcoin command is calling getBcoin() so it is showing the last generated image and not a new image.

Thanks for the reported BUG, this correction will be made.

**Comment by newerton** [comment]
@agsfmlcx New update, with correction of Telegram commands. Could you test the /map and /bcoin command?
