### ISSUE TITLE
feature: Multi-account no Linux e MacOS

### ISSUE THREAD

**Issue by jpzin** [newerton/bombcrypto-bot#33]
E aí meu mano! Tudo certo?

Tô com dois problemas aqui para rodar em MacOS.

1) O multi-account, por mais que eu coloque como "True", no terminal ele diz que está DISABLED. Ele não funciona em posix? É só nt mesmo?

2) Mesmo rodando em uma conta, aparentemente ele starta corretamente (recebo a notificação do Telegram), mas ele não loga e já vai direto nessa parte aqui:

📱 Initializing Telegram...
🧾 Multi account DISABLE
🏢 Search for heroes to work
⚒️ Sending heroes with green stamina bar to work!
🦸 0 total heroes sent since the bot started

Já tentei iniciar com o mapa aberto, com a tela de heróis aberta, e mesmo assim não rola.

Sabe o que pode ser?

Abraço e valeu por compartilhar o projeto!

**Comment by newerton** [comment]
@jpzin Tranquilo?

A lib oficial que identifica os programas aberto no sistema operacional, só funciona por enquanto em Windows.

Segue a documentação da biblioteca:

PyGetWindow
A simple, cross-platform module for obtaining GUI information on and controlling application's windows.
Still under development. **Currently only the Windows platform is implemented**. If you want to help contribute, please contact al@inventwithpython.com!_

--

Mas não se preocupe, existem um fork do repositório oficial (pygetwindow) que o desenvolvedor implementou o linux e mac.
Eu fiz a cópia do código e adicionei na pasta: ./src/external/pygetwindow
Mas ainda não foi implementada, mas essa semana será feita a implemetanção para Linux e MacOS o MultiAccount

**Comment by newerton** [comment]
@jpzin Consegue me ajudar a testar no MacOS?

A alteração seria a seguinte. No arquivo ./src/multi_account.py tem essas linhas aqui:

Linha 7,8 e 9
```python
if os.name == 'nt':
    import pygetwindow as botMultiAccount
    from pygetwindow import PyGetWindowException
```

Você precisa apagar essas 3 linhas, e adicionar esse código aqui:
```python
import src.external.pygetwindow as botMultiAccount
from src.external.pygetwindow import PyGetWindowException
```

Como é outra biblioteca, eu fiz o teste no Windows e funcionou, veja se vai funcionar no MacOS o MultiAccount

**Comment by jpzin** [comment]
E ae grande @newerton.

Veja aí, aparentemente não deu:
<img width="520" alt="Screen Shot 2022-01-19 at 14 50 32" src="https://user-images.githubusercontent.com/40303410/150231198-f3c35d30-9393-447d-9e0e-3ee509e908cf.png">

**Comment by newerton** [comment]
@jpzin Blz, já sei o que pode ter acontecido. Para não demorar a comunicação, me manda uma mensagem no Telegram (https://t.me/newerton)

**Comment by monoufuuma** [comment]
@newerton tudo bem amigo? grato demais pelo projeto.
estou tentando rodar multi acc no ubuntu, mas ainda está com o problema PyGetWindow. 
existe uma forma de contornar isso? colocar pra rodar ou ainda nao tem suporte? desculpe, sou um pouco leigo no assunto mas estou pesquisando.

**Comment by newerton** [comment]
@monoufuuma Nos testes que estou fazendo aqui o Ubuntu não está reconhecendo as janelas do jogo, ele executa as ações mas não identificar as janelas, ja estou encontrando outras soluções.

**Comment by monoufuuma** [comment]
Obrigado pela rápida resposta. 
Isso é uma ótima notícia! Fico aqui na torcida que dê certo. Salvaria demais aqui pra mim! Rodo o bomb numa VPS com Ubuntu e gostaria muito de poder usar multi acc. Ficaria muito grato ($$$) pela sua ajuda! Estarei observando os updates. Abs.

**Comment by newerton** [comment]
@monoufuuma Agora com a nova atualização, o bot está funcionando no linux em multiacc.
