### ISSUE TITLE
ImportError: cannot import name 'Update' from 'telegram'

### ISSUE THREAD

**Issue by ruanzxto** [newerton/bombcrypto-bot#34]
Traceback (most recent call last):
  File "index.py", line 7, in <module>
    from src.services.telegram import Telegram
  File "/home/bomb/Desktop/newbot/src/services/telegram.py", line 2, in <module>
    from telegram import Update
ImportError: cannot import name 'Update' from 'telegram' (/home/bomb/.local/lib/python3.8/site-packages/telegram/__init__.py)

**Comment by newerton** [comment]
@ruanzxto Try: python install -r requirements.txt --force

**Comment by ruanzxto** [comment]
Fiz aqui, e deu a mesma coisa :( 
uso uma maquina linux onde rodava outro bot, que tinha envio de dados pelo telegram. Porem esse quando rodei o requirements.txt instalou tudo, porem nao executa e da o erro acima

**Comment by Hasslek** [comment]
> 

I have the same problem, i tried this command and didn't solve the problem.

**Comment by newerton** [comment]
> Fiz aqui, e deu a mesma coisa :( uso uma maquina linux onde rodava outro bot, que tinha envio de dados pelo telegram. Porem esse quando rodei o requirements.txt instalou tudo, porem nao executa e da o erro acima

Remove o python 3.8 e instala o 3.9

**Comment by newerton** [comment]
> > 
> 
> I have the same problem, i tried this command and didn't solve the problem.

Same problem with Telegram?

**Comment by Hasslek** [comment]
> 

Yes, with telegram. I can't start the bot beucause it says:

ImportError: cannot import name 'Update' from 'telegram' (/usr/local/lib/python3.8/dist-packages/telegram/__init__.py)

**Comment by newerton** [comment]
@Hasslek Remove the "telegram==0.0.1" inside the requeriments.txt, and execute the pip install

https://stackoverflow.com/questions/66829415/importerror-cannot-import-name-bot-from-telegram

**Comment by Hasslek** [comment]
> @Hasslek Remove the "telegram==0.0.1" inside the requeriments.txt, and execute the pip install
> 
> https://stackoverflow.com/questions/66829415/importerror-cannot-import-name-bot-from-telegram

Well, this didn't fix the problem :(

I tried this, and removing the telegram librarie but still have the same error.

**Comment by newerton** [comment]
> > @Hasslek Remove the "telegram==0.0.1" inside the requeriments.txt, and execute the pip install
> > https://stackoverflow.com/questions/66829415/importerror-cannot-import-name-bot-from-telegram
> 
> Well, this didn't fix the problem :(
> 
> I tried this, and removing the telegram librarie but still have the same error.

Which your python version?

Use: python --version

Solution
Elisson Andrade, [01/17/2022 12:03]
in a zero config of linux ubuntu 20.04 I had to install python3, then I ran an alias python=python3, then I ran the requirements.txt ... for me, the only thing I needed afterwards was to solve some problems with telegram , by the command pip3 install --upgrade --force-reinstall python_telegram_bot

**Comment by ruanzxto** [comment]
Agora consegui fazer funcionar, porem quando dou /bcoin ele da mensagem no bot que o telegram ta offline
só que as outras infos ele manda

**Comment by newerton** [comment]
> Agora consegui fazer funcionar, porem quando dou /bcoin ele da mensagem no bot que o telegram ta offline só que as outras infos ele manda

Posta aqui sua solução para quem tiver mais problemas.

Se você tiver usando MultiAcc, o /bcoin e o /map está desativado no bot.

**Comment by ruanzxto** [comment]
Eu formatei a maquina linux, e instalei só o que ta no requirements.txt e apaguei o telegram==0.0.1 dele e fiz o que passou ali anteriormente pip3 install --upgrade --force-reinstall python_telegram_bot

**Comment by ruanzxto** [comment]
Uso a versao de 1 conta só, porem ta dando o aviso que o telegram ta offline quando dou /bcoin

**Comment by newerton** [comment]
> Uso a versao de 1 conta só, porem ta dando o aviso que o telegram ta offline quando dou /bcoin

Consegue enviar o print do erro?

**Comment by ruanzxto** [comment]
![image](https://user-images.githubusercontent.com/97133292/149800994-b7528917-7702-4ecc-b522-7ab90e57d7df.png)

**Comment by ruanzxto** [comment]
e no telegram veio a mensagem "Processing..."

**Comment by newerton** [comment]
> e no telegram veio a mensagem "Processing..."

Lembrei o que pode ser.
Quando finaliza o mapa, o bot gera 2 imagens, do mapa e dos BCOINS.

No bot do telegram, esses comandos estão buscando essas imagens. O correto é executar o comando do bot para tirar um novo print do mapa, e não buscar a imagem já gerada, por isso está com erro o seu bot, por que essa imagem não foi gerada.

Mas tem uma Issue com esse bug: https://github.com/newerton/bombcrypto-bot/issues/32

Vou esperar o lançamento do Marketplace que é amanhã, ai já faço essa correção.

**Comment by ruanzxto** [comment]
Sabe me dizer qual comando é, porque não achei aqui, só pra não ter que esperar terminar o mapa

**Comment by newerton** [comment]
> Sabe me dizer qual comando é, porque não achei aqui, só pra não ter que esperar terminar o mapa

Então, tem que esperar eu terminar essa correção. Por que os comandos /map e /bcoin pega a imagem gerada quando o mapa é finalizado. Se por acaso você digitar (hoje) o /map ele vai pegar sempre a imagem do mapa inicial e não do mapa atual. Por isso necessita desta correção.

**Comment by newerton** [comment]
@ruanzxto Faz a atualização do projeto, e testa o comando /map e /bcoin

**Comment by ruanzxto** [comment]
![image](https://user-images.githubusercontent.com/97133292/149824928-04bdc1b6-8975-4e17-bb0d-ee47a1ef5cdb.png)
fui tentar dar um update mas não vai. 

Fiz atualização manual mesmo, baixando de novo e alterando apenas as pastas que tiveram arquivos alterados. Vou testar agora

**Comment by ruanzxto** [comment]
Fiz atualização manual mesmo, baixando de novo e alterando apenas as pastas que tiveram arquivos alterados. Vou testar agora

**Comment by ruanzxto** [comment]
Agora funcionou, acessei a maquina remotamente e vi ao vivo ele indo no bau tirando print pra enviar
