### ISSUE TITLE
File update error config.yaml

### ISSUE THREAD

**Issue by anmx14** [newerton/bombcrypto-bot#37]
when i run the bot i get the following error: 

File that needs updating: ./config/config.yaml

***************************
***** UPDATE REQUIRED *****
***************************
Key added:
['threshold']['jail']
Erro in validation configs

**Comment by newerton** [comment]
@anmx14 You need add the jail in threshold. Otherwise, the bot will give an error when calculating the map estimate.

See: https://github.com/newerton/bombcrypto-bot/blob/main/config/EXAMPLE-config.yaml

**Comment by jiraspiom** [comment]
estou configurando o campo chat_ids: ["YOUR_CHAT_ID_1", "YOUR_CHAT_ID_2"]
não sei o que deveria colocar ai
eu estou recebendo um erro quando chamo o comando /chat_id
"Your id is:{update.effect_user.id}"
a variavel contida no campo {} nao esta sendo atualizar com o valor.

**Comment by newerton** [comment]
@jiraspiom Se você não adicionar o seu CHAT_ID, é obvio que vai dar erro nos comandos, a integração do Telegram não vai saber para quem enviar a mensagem.

Você precisa enviar um comando /start para o bot @userinfobot
E pegar o seu token com @BotFather

**Comment by anmx14** [comment]
> @anmx14 You need add the jail in threshold. Otherwise, the bot will give an error when calculating the map estimate.
> 
> See: https://github.com/newerton/bombcrypto-bot/blob/main/config/EXAMPLE-config.yaml

Thanks <3
