### ISSUE TITLE
Integração Telegram

### ISSUE THREAD

**Issue by nielkp** [newerton/bombcrypto-bot#39]
boa noite amigo, vi que voce é BR, estou tendo dificuldade pra colocar o bot do telgram, poderia me ajudar? já peguei o token do botfather e dei /star la no chat

**Comment by newerton** [comment]
Você precisa criar um bot em @Botfather. Depois de criar o bot, digite /token para gerar o token.
Depois disso, você precisa enviar um comando (/start) para o bot @userinfobot

**Comment by nielkp** [comment]
Então eu fiz isto, peguei o token, e envitei um /star no chat do bot que eu criei. porem recebo isto: 2022-01-17 20:10:09 - Error to send telegram message. See configuration file

**Comment by nielkp** [comment]
[telegram.txt](https://github.com/newerton/bombcrypto-bot/files/7885156/telegram.txt)
coloquei assim, correto?

**Comment by nielkp** [comment]
chat_ids: ["YOUR_CHAT_ID_1", "YOUR_CHAT_ID_2"]
botfather_token: "5048726132:AAHrhz9srrTpV38DeoqyXMUS_1ywAsDMd28"
enable_coin_report: true
enable_map_report: true
format_of_image: "jpg"
enable_emergency_call: false

**Comment by nielkp** [comment]
arquivo do .txt pra nao prescisar baixar

**Comment by newerton** [comment]
@nielkp Deletei seus post, por causa do seu token.

Mas é isso mesmo.

Agora você precisa pegar seu chat_id com o @userinfobot

E adicionar aqui:

chat_ids: ["1234567890"]

**Comment by nielkp** [comment]
carambra, muito obrigado! salvou a pátria! fico grato amigo.

**Comment by newerton** [comment]
@nielkp Funcionou?

**Comment by nielkp** [comment]
funcionou sim :)
