### ISSUE TITLE
Mult-telas e emoji

### ISSUE THREAD

**Issue by caslujpg** [newerton/bombcrypto-bot#41]
Boa tarde, gostaria de saber se teria como me ajudar na questão de mult telas, uso 3 telas aqui equando estou com elas ativadas nao consigo fazer o bot rodar, mesmo colocando o numero da tela etc, só quando desabilito

**Comment by newerton** [comment]
@lucgregor Me passa qual sistema operacional está usando e a versão do python (python --version)

**Comment by caslujpg** [comment]
windows 10, 3.9.9

**Comment by newerton** [comment]
Quando você for trabalhar com Multi Account, você só precisa ativar o multi_account enable, o valor do monitor_to_use deixa sempre 1. Esse monitor_to_use é quantidade de monitor.

Para trabalhar com multi account, você precisa está com as 3 janelas aberta na página do jogo e executar o bot. Ele vai fazer o login automatico para você e colocar os heróis para trabalhar.

**Comment by caslujpg** [comment]
então, eu quero trabalhar com 1 conta só, mas tenho 3 monitores, porem quando os 3 monitores estao habilitados o bot nao roda

**Comment by newerton** [comment]
> então, eu quero trabalhar com 1 conta só, mas tenho 3 monitores, porem quando os 3 monitores estao habilitados o bot nao roda

Entendi, achei que queria trabalhar com multiaccount. Se vai trabalhar com 1 conta, você só pode usar o browser em 1 navegador, ele não pode fica extendido para os 3 monitores. Faz assim então no config.yaml, altera o monitor_to_use para 2 e depois para 3, por que vc tem 3 monitores.

**Comment by caslujpg** [comment]
sim, ja fiz isso mas continua dando erro

**Comment by newerton** [comment]
> sim, ja fiz isso mas continua dando erro

O erro aparece no terminal do windows? Por que se você tem 3 monitores, e o windows configura como monitor 1, 2 e 3. E se nenhum desses números está funcionando, seu windows ou navegador pode está com zoom que não é o 100%.

**Comment by caslujpg** [comment]
não, ele nao aparece erro, só o mouse não mexe para lugar nenhum da tela e identifica que nao tem herois para trabalhar sem nem conferir etc

**Comment by caslujpg** [comment]
se tiver como até compartilho tela com voce se tiver discord para te mostrar em tempo real

**Comment by newerton** [comment]
> se tiver como até compartilho tela com voce se tiver discord para te mostrar em tempo real

Me manda seu user do discord.

**Comment by caslujpg** [comment]
caslu_jpg#2011

**Comment by caslujpg** [comment]
caslu_jpg#2011
mandei dnv para não ficar editado e passar batido
