### ISSUE TITLE
Duvida sobre problema no linux

### ISSUE THREAD

**Issue by ruanzxto** [newerton/bombcrypto-bot#42]
Estou configurando o bot em uma maquina pra um amigo, porem me deparei com o seguinte erro ao executar 
![image](https://user-images.githubusercontent.com/97133292/149940019-057d36be-759c-4cf4-b578-002002d7e1e1.png)
![image](https://user-images.githubusercontent.com/97133292/149940030-3cf250cf-e146-45f2-8978-b0eb8b531efd.png)

**Comment by newerton** [comment]
Me passa qual a versão do Ubuntu e a configuração do PC.

**Comment by ruanzxto** [comment]
![image](https://user-images.githubusercontent.com/97133292/149958502-3e05a89a-ff59-4b81-8ddf-7a9d9c93ddb0.png)


> Me passa qual a versão do Ubuntu e a configuração do PC.

**Comment by newerton** [comment]
@ruanzxto Foi instalado em uma VM ou VPS?

Executa o seguindo comando: pip3 install --upgrade --force-reinstall mss

E faz uma alteração no arquivo ./src/desktop.py

```python
import numpy as np
import mss

class Desktop:
    def importLibs(self):
        from src.config import Config
        self.config = Config().read()

    def printScreen(self):
        self.importLibs()
        with mss.mss() as sct:
            monitorToUse = self.config['app']['monitor_to_use']
            monitor = sct.monitors[monitorToUse]
            print(monitor) # <-- adiciona essa linha
            sct_img = np.array(sct.grab(monitor))
            return sct_img[:, :, :3]
```

Tem um print() na linha 14, executa o bot, e veja o que o bot vai mostrar no terminal.

**Comment by ruanzxto** [comment]
Fiz o Linux rodar em X11 e foi de boa, valeu
