### ISSUE TITLE
Zoom no navegador

### ISSUE THREAD

**Issue by neemiasbj** [newerton/bombcrypto-bot#44]
Boa tarde,

Tenho 4 contas, meu monitor é pequeno, então uso zoom de 50%, o bot atende?

**Comment by newerton** [comment]
@neemiasbj Pode ser com monitor pequeno, mas o Sistema Operacional e o Navegador precisa está com zoom de 100%, por causa dos reconhecimento das imagens está todos com zoom 100%. Qualquer mudança no zoom, o bot não reconhece.
