### ISSUE TITLE
Feature: Novos comandos via Telegram (workall, restall)

### ISSUE THREAD

**Issue by mgramelich** [newerton/bombcrypto-bot#45]
Boa tarde, gostaria de deixar a sugestão de inclusão dos comandos /workall e /restall para aproveitar os novos botões incluídos no jogo.

**Comment by newerton** [comment]
@mgramelich Novos comandos adicionado no Telegram, faça o update do projeto.

**Comment by ruanzxto** [comment]
@newerton aqui o comando executa mas não clica no ALL, tanto pra trabalhar, quanto pra descansar. Ele só abre a lista e fecha e vai pro mapa

**Comment by ruanzxto** [comment]
> @newerton aqui o comando executa mas não clica no ALL, tanto pra trabalhar, quanto pra descansar. Ele só abre a lista e fecha e vai pro mapa

esquece, agora foi
porem na 3ª vez que executei só

**Comment by newerton** [comment]
@ruanzxto Você tem que configurar o threshold
