### ISSUE TITLE
How to configure Telegram?

### ISSUE THREAD

**Issue by Hasslek** [newerton/bombcrypto-bot#51]
I have the bot on botfather, but in the config appears something like;

chat_ids: ["YOUR_CHAT_ID_1", "YOUR_CHAT_ID_2"]

Where i get this two IDs? i know how to get my telegram id, but what is the other ID that i need?

**Comment by newerton** [comment]
Send /start to https://t.me/userinfobot.

You don't need to put the CHAT_ID_1 and CHAT_ID_2, just add the CHAT_ID_1, if you have another chat, then you add it.

Example:
chat_ids: ["1234567890"]

**Comment by Mobuis** [comment]
I think an explanation in the README.MD could be a good idea for beginners 🙄 
(I can do a PR for it if you want, surely tomorrow)

**Comment by Hasslek** [comment]
I have put my Telegram ID and the botfather bot token and the following appears in the console:

Error to send telegram message. See configuration file

In theory everything is fine but this error occurs when starting the bot in the console.

**Comment by nielkp** [comment]
Hi, you need
Send /start to https://t.me/userinfobot.

after this set chat ID on
chat_ids: ["1234567890"]

and to finish put you BotFather token!

like this:
chat_ids: ["123123123"]
botfather_token: "123123123"
enable_coin_report: true
enable_map_report: true
format_of_image: "jpg"
enable_emergency_call: false

**Comment by Hasslek** [comment]
> 
I have it exactly configured as you indicate and it gives this problem.

I have tried both on my computer and on a server, but the problem persists.

I do not understand what can happen, everything is configured as you have told me.

**Comment by Hasslek** [comment]
Well, I think I've fixed it.

What I was missing was to start the bot in Telegram.

yes it sounds ridiculous
