### ISSUE TITLE
Recarregar pagina depois de X tempo?

### ISSUE THREAD

**Issue by nielkp** [newerton/bombcrypto-bot#54]
Bom dia amigo, esta acontecendo de muitos maps terem um block com vida infinida onde o mesmo nao quebra, e é nescessario Recarregar a pagina do BombCrypto.io, é possivel colocar o Bot para a cada X tempo definido ele recarregar a pagina e entra novamente no game? aconteceu comigo isto duas vezes já, onde só fica um block infinito é muito triste kkks

**Comment by newerton** [comment]
@nielkp Tem outra issue com este mesmo problema, coloquei uma solução temporária que você pode fazer. Como é bug do jogo não posso implementar isso, mas tem uma solução já.

https://github.com/newerton/bombcrypto-bot/issues/52

**Comment by nielkp** [comment]
ah sim tranquilo, obrigado! ✌️
