### ISSUE TITLE
Unable to automatically reconnect

### ISSUE THREAD

**Issue by Hasslek** [newerton/bombcrypto-bot#55]
Sometimes when the game suffers some unexpected disconnection or error the bot will try to reconnect.

So far so good, however as soon as it detects the "Connect wallet" button and clicks it, a Metamask pop-up appears.

This pop-up is to sign or reject the contract to finally enter Bombcrypto.

![imagen](https://user-images.githubusercontent.com/31199840/150390678-3989313e-36ae-4cf6-81a9-a9578dc14691.png)

The problem here is that it never clicks the "sign" button when trying to reconnect, so I have to watch out and reconnect manually.

Is there a way to disable signing, or make reconnect work properly on the bot?

**Comment by Druidou** [comment]
your metamask must be in English look in the file bombcrypto-bot-main\images\themes\default

![metamask_sign_button](https://user-images.githubusercontent.com/97760292/150416887-3852b915-742b-43ac-8951-40b76358499d.png)

I think this will solve your problem , or modify the image in your file

**Comment by Hasslek** [comment]
Yep, fixed. Thanks!
