### ISSUE TITLE
Dica de comando

### ISSUE THREAD

**Issue by ruanzxto** [newerton/bombcrypto-bot#58]
Como tem bastante gente com bug de Bloco que não quebra, ou baú infinito, é acaba ficando no mapa com 1 baú ou 1 bloco. Poderia adicionar /f5 pra que o bot desse auto ctrl+f5 pra relogar e desbugar

**Comment by newerton** [comment]
@ruanzxto Coloquei uma solução aqui. 

https://github.com/newerton/bombcrypto-bot/issues/52

Não vou implementar por que é um bug do jogo, e daqui a pouco os dev tem que resolver hehe

**Comment by ruanzxto** [comment]
É que logar na máquina virtual só pra isso é chatao kkkk aí por isso pensei, como minha vm fica no Google aí dou só /print pra saber como tá
