### ISSUE TITLE
bug: Mensagens de comandos Telegram

### ISSUE THREAD

**Issue by nielkp** [newerton/bombcrypto-bot#60]
Boa tarde amigo, eu notei que o comando /restall não retorna nenhum aviso de que a ação foi concluida, só estou relatando isso, pois o /workall devolve uma mensagem falando que todos foram trabalhar ✌️

**Comment by ruanzxto** [comment]
Aqui também tinha notado isso, e copiei o código do workall mudei o emoji e coloquei pra alertar no restall

**Comment by newerton** [comment]
@nielkp Vou adicionar essa mensagem, já te aviso.

**Comment by nielkp** [comment]
top mano, seria legal colocar aquela "processando" tambem quando digita o comando antes de ser concluido

**Comment by newerton** [comment]
Corrigido.
