### ISSUE TITLE
Clicando sempre em cima dos mesmos

### ISSUE THREAD

**Issue by ruanzxto** [newerton/bombcrypto-bot#62]
Notei que no multiacc quando tem muitos heros green antes do scroll, ele bota todos e fica clicando neles direto sem dar o scroll pra ver se tem mais... Isso seria um erro? https://user-images.githubusercontent.com/97133292/150616141-861458d5-471c-4e44-a1d5-5d0de0a1c1a1.mp4

**Comment by newerton** [comment]
@ruanzxto Vi o vídeo, cadê o cursor do mouse? Estranho ele está indo heróis por heróis, e não está clicando no botão WORK, o que você pode fazer é habilitar o debug, e verificar na lista de heróis se o bot identifica as barras de staminas verde e os botões verde. Ai depois vc vai ajustando o threshold.

**Comment by ruanzxto** [comment]
Na real ali que tava por acesso remoto, mas ele fica clicando em work só que dos que ele já clicou, no vídeo tive que cortar um pedaço por causa do tamanho aqui. Ele clica em uns 3 ou 4 e depois fica só neles, porém no single acc não tive esse problema

**Comment by newerton** [comment]
Aumenta o heroes_green_bar para 0.9 ou 0.95, para o work_button também, vai aumentando de valores decimais 1 por 1
