### ISSUE TITLE
feature: (Ideia) Auto refresh page

### ISSUE THREAD

**Issue by HudsonnBR** [newerton/bombcrypto-bot#65]
Uma ideia que eu tive e serve de sugestão, devido a esse bug de bloco e bau inquebravel, seria a adição de uma função pra dar um refresh na página.
Dai ter, la no arquivo se config, a opcao de ativar ou desativar essa funcao e escolher o intervalo para o refresh, assim como ha o de setar o intervalo pra envio dos herois.
Fui claro? kkkk

Agradeço a atencão.

**Comment by newerton** [comment]
@HudsonnBR Coloquei um autokey para atualizar a página, depois que os heróis é escolhido pelo bot. Não vai ser implementando, por que é um bug temporário do jogo, e os devs são obrigado a corrigir.

https://github.com/newerton/bombcrypto-bot/blob/main/src/treasure_hunt.py#L42

Vai nesse arquivo e nessa linha, e remove a primeira # da linha, que o autokey vai funcionar.

**Comment by HudsonnBR** [comment]
> @HudsonnBR Coloquei um autokey para atualizar a página, depois que os heróis é escolhido pelo bot. Não vai ser implementando, por que é um bug temporário do jogo, e os devs são obrigado a corrigir.
> 
> https://github.com/newerton/bombcrypto-bot/blob/main/src/treasure_hunt.py#L42
> 
> Vai nesse arquivo e nessa linha, e remove a primeira # da linha, que o autokey vai funcionar.

Ahh, perfeito! Farei isso!
Muito obrigado
