### ISSUE TITLE
[Sugestões] Novos comandos do telegram

### ISSUE THREAD

**Issue by zGabriel144** [newerton/bombcrypto-bot#70]
Algumas sugestões para comandos do telegram

1 - Comando para mandar trabalhar apenas herois de determinada raridade. Ex: /workallepic ; /workallcommon

2 - Comando para mandar trabalhar os herois com stamina cheia.

3 - Comando para mandar trabalhar os herois com stamina verde.

4 - Comando para printar a pagina de herois.

**Comment by newerton** [comment]
Criei uma nova issue só com os comandos do telegram.

https://github.com/newerton/bombcrypto-bot/issues/73
