### ISSUE TITLE
Erro telegram

### ISSUE THREAD

**Issue by bvieira15** [newerton/bombcrypto-bot#72]
Bom dia, estou com erro em receber os arquivos no Telegram, poderiam me auxiliar??
![botlog](https://user-images.githubusercontent.com/98408289/151006247-9cf5f940-3492-49e5-ad67-98ccde905276.PNG)
![bot arq](https://user-images.githubusercontent.com/98408289/151006258-d7eaad93-d283-441e-aeb5-2f399335d9c2.PNG)

**Comment by newerton** [comment]
@bvieira15 Você precisa adicionar o CHAT_ID nas configurações. Entra no Telegram @userinfobot e envia uma mensagem /start, que esse bot vai retornar um id para você.

**Comment by bvieira15** [comment]
AGora esta com este erro

![image](https://user-images.githubusercontent.com/98408289/151022118-b01bf6b5-d785-4d07-9936-9eaff13fd49c.png)

**Comment by bvieira15** [comment]
Asssim mesmo ne?
![image](https://user-images.githubusercontent.com/98408289/151022276-c288458a-5ee9-47a4-ae15-3b1c9ea90039.png)

**Comment by newerton** [comment]
@bvieira15 Está certo, se observar a última linha dos erros, está informando (Unauthorized). Você está sem permissão de acesso ao bot, você criou esse token pelo bot @BotFather ? Tenta apagar esse bot e criar outro.

**Comment by bvieira15** [comment]
Agora deu certo, muito obrigado.
Como uso os comandos nele??

**Comment by newerton** [comment]
> Agora deu certo, muito obrigado. Como uso os comandos nele??

Digita / no campo de mensagem, que vai aparecer  todos os comandos

**Comment by bvieira15** [comment]
pra mim não apareceu
