### ISSUE TITLE
[Future] New Telegram commands

### ISSUE THREAD

**Issue by newerton** [newerton/bombcrypto-bot#73]
Alguns comandos para adicionar no bot do Telegram. 
Some commands to add in Telegram bot. 

- [ ]  Trabalhar os heróis com stamina cheia. (/workall_greenbar)
- [ ]  Trabalhar os heróis com stamina verde. (/workall_fullbar)
- [ ]  Printscreen da lista de heróis. (/print_heroeslist)
- [ ]  Trabalhar apenas heróis de determinada raridade. (/workall_epic , /workall_common)
- [ ]  Modo multiaccount (/map_1, /bcoin_1, /workall_1, /restall_1, ...)

## Observações.
**Comando para printar a página de herois**
As imagens vai depender da quantidade de **scroll_attempts** configurado. O bot não vai fazer merge da lista para enviar 1 imagem,  após cada scroll o bot vai enviar um print da lista.

**Modo multiaccount **
Esse comando pode levar mais tempo, pela complexidade. O Bot tem que pegar a quantidade de tela ativa do multi_account.py e criar todos os comandos novamente adicionando o underline depois do comando com o número da janela ativa.

**Comment by ghost** [comment]
@newerton e como faço para ativar esse comandos no telegram?

**Comment by newerton** [comment]
@VGNChris É novos comandos, ainda não foram adicionados.

**Comment by nielkp** [comment]
Bom dia @newerton , eu tenho mais uma ideia de comando para adicionar, que acho que pode ser bastante util para quem esta a distancia, apenas pelo telegram, seria o comando /reload ou /refresh para ele recarregar a pagina do bomb caso o usuario digite esse comando.

**Comment by nielkp** [comment]
@newerton tbm percebi que o comando /workall neste ultimo update esta apresentando problemas, ou ele nao faz nada, ou ele abre o modo historia, ou ate mesmo abre os herois mas ja fecha em seguida, sem coloca-los pra trabalhar

**Comment by jmatheusbueno** [comment]
saaalve @newerton, identifiquei uma vulnerabilidade nos comandos do bot via telegram, a gente pode trocar uma ideia?

**Comment by newerton** [comment]
@jmatheusbueno Eae João, manda ae, vamos resolver essa vulnerabilidade. Se for muito critica te passo um contato meu.

**Comment by kerferber** [comment]
Pelo visto foi corrigido, mas fiquei curioso quanto a vulnerabilidade. Mais detalhes?

**Comment by jkacza** [comment]
Os comandos do telegram funcionam? Não estou conseguindo aqui... Alguém ajuda poderia ajudar?

**Comment by newerton** [comment]
> Os comandos do telegram funcionam? Não estou conseguindo aqui... Alguém ajuda poderia ajudar?

@jkacza Você precisa do chat_id e do token do botfather. E habilitar o telegram no config.yaml.
