### ISSUE TITLE
Forma do Multi account e feature de reload de pagina.

### ISSUE THREAD

**Issue by kendikaku** [newerton/bombcrypto-bot#74]
Boa tarde Newerton tudo bom?
será que existe a possibilidade de colocar uma feature de reload da pagina por tempo determinado?
como o bug dos baú e das pedras que não estão quebrando não foi resolvido ainda estou a mercê de plugin no navegador e todos sabemos que plugin junto com metamask pode dar problema.

outra coisa e se você ja viu esse bot funcionando?
ele funciona com as contas lado a lado sem ficar dando ALT TAB,
não sei se seria algo bom para colocar no seu bot.

https://github.com/MatheusHAS/bombcrypto-bot

**Comment by newerton** [comment]
@Japa18244 Tranquilo? Essa implementação do refresh está no arquivo heroes.py (https://github.com/newerton/bombcrypto-bot/blob/main/src/heroes.py#L116), é só remover o primeiro # da linha que já vai está funcionando. Ele dá o refresh da página depois de buscar os heroes e enviar para o mapa. Então o refresh é executado conforme o seu **send_heroes_for_work** foi configurado.
Só não vai ser implementando, por que terei que alterar o arquivo config.yaml, como tem muitos usuários usando, eles vão receber aviso de update e quando atualizar vai precisar adicionar a nova chave no config.yaml, como é um bug, que espero que seja corrigido, depois terei que tirar essa funcionalidade de refresh.

Sobre o multiaccount deste bot, ele funciona de 2 formas, o modo lado a lado, você pode colocar 4 janelas (4 contas), que o bot vai maximizar janela por janela e executar a ações que precisa, depois que 1 janela é finalizada, o bot retornar ela no mesmo lugar que ela estava antes.

**Comment by kendikaku** [comment]
> @Japa18244 Tranquilo? Essa implementação do refresh está no arquivo heroes.py (https://github.com/newerton/bombcrypto-bot/blob/main/src/heroes.py#L116), é só remover o primeiro # da linha que já vai está funcionando. Ele dá o refresh da página depois de buscar os heroes e enviar para o mapa. Então o refresh é executado conforme o seu **send_heroes_for_work** foi configurado. Só não vai ser implementando, por que terei que alterar o arquivo config.yaml, como tem muitos usuários usando, eles vão receber aviso de update e quando atualizar vai precisar adicionar a nova chave no config.yaml, como é um bug, que espero que seja corrigido, depois terei que tirar essa funcionalidade de refresh.
> 
> Sobre o multiaccount deste bot, ele funciona de 2 formas, o modo lado a lado, você pode colocar 4 janelas (4 contas), que o bot vai maximizar janela por janela e executar a ações que precisa, depois que 1 janela é finalizada, o bot retornar ela no mesmo lugar que ela estava antes.

ah sim, essa forma que voce me passou daria certo, mas eu nao coloco meus herois pra trabalhar de hora em hora ou de 30 em 30 minutos, eu deixo de 10 em 10 pra colocarem sempre com a estamina verde, a sua solução ai talvez não daria certo pra mim, mas como voce ai mesmo disse que não pode alterar essa funcção pois é um bug que vai ser consertado (vai saber quando), vi que da pra fazer essa alteração na verificação de capthca, será que você consegue me passar os comandos?

Edit: desconsidera já vi outros issues fechados a respeito disso,
Obrigado pelo incrivel trabalho, melhor bot de todos.
