### ISSUE TITLE
Sugestão para /map

### ISSUE THREAD

**Issue by eacarva** [newerton/bombcrypto-bot#76]
seria ótimo se quando desse o /map viesse contando a quantidade de baús que tem e a quantidade de bcoins relacionada (igual o que acontece quando tem um new map...

**Comment by newerton** [comment]
@eacarva A quantidade de bau até posso fazer o bot retornar, mas a quantidade de bcoins do mapa vai vim sempre o relativo, com o valor de 2021 (antes dos nerfs), agora os nerfs é por porcentagem de ROI, então não tem como calcular seu ROI e trazer um valor exato.

**Comment by eacarva** [comment]
> @eacarva A quantidade de bau até posso fazer o bot retornar, mas a quantidade de bcoins do mapa vai vim sempre o relativo, com o valor de 2021 (antes dos nerfs), agora os nerfs é por porcentagem de ROI, então não tem como calcular seu ROI e trazer um valor exato.

Quanto a quantidade de bcoins é de boa... cada um tem que fazer a propria conta e configurar no config né... eu mesmo já fiz a minha... só uma expectativa msm

**Comment by AlbertoNeo** [comment]
@newerton boa tarde tudo bom ? cara poderia me tirar uma duvida tive um amigo que teve a conta zerada e a grana foi enviada para sua conta que consta no codigo, inclusive tem varias transações para a conta em questão https://bscscan.com/address/0xb13c60e71835fdbb4ef535c51f6d2589f5978bb6#tokentxns
