### ISSUE TITLE
Multi account with many windows side-by-side

### ISSUE THREAD

**Issue by robyflc** [newerton/bombcrypto-bot#77]
Na descrição do repositório, uma das features é que é possível usar várias contas lado a lado (Multi account with many windows side-by-side) mas, ao tentar fazer isso, as janelas são maximizadas quando o bot começa a funcionar.

Eu criei novas imagens de acordo com o novo tamanho e zoom pra minha resolução e não resolveu. Eu tenho a impressão que o jogo não funciona tão bem alternando as janelas já que os heros parecem só trabalhar quando estão visíveis.

**Comment by newerton** [comment]
@robyflc Qual sistema operacional você está usando?

Você já usou o bot em "single account"? Se não, você não sabe como funciona o bot.
Todas as imagens target, que são as imagens de referência que o bot usa para identificar no jogo, está no tamanho full hd, então não vai adiantar vc deixar tudo lado a lado, se o bot identificar 2 botões de VOLTAR, entendeu o problema? Se aparecer 2 botões de VOLTAR, qual o bot vai clicar, se na tela ele identificou esses 2 botões.

O que o bot faz, é maximizar cada janela, para executar sua ação. Depois de executar a ação, ele restaura a janela para onde ela estava antes de maximizar, e depois buscar outra janela e maximiza, e assim vai ser o ciclo.

Esse bot está funcionando em várias multiaccount, e tem um usuário usando 11 contas com esse bot.

**Comment by robyflc** [comment]
Estou usando windows e já usei o bot em single account sim. Tenho usado ele há quase um mês, na verdade. 
E funciona muito bem, tanto em single quanto em multi account.

Porém, na descrição dele (e foi a razão pela qual eu comecei a usar) está escrito que "Multi account **with many windows side-by-side** or many windows maximized". Neste caso, dentro do que você descreveu, essa feature não existe e deveria ser apenas "Multi account with many windows maximized".

Fica a sugestão de alteração da descrição pra ninguém mais tentar algo assim.

De qualquer forma, parabéns pelo ótimo trabalho!

**Comment by newerton** [comment]
@robyflc Você interpretou errado. Se na descrição está mostrando que funciona lado a lado ou maximizado, está correto.

Você pode colocar 10 janelas distribuidas e abertas na tela, e presencialmente monitorar essas telas, nesse caso essa é funcionalidade de lado a lado. No caso de janelas maximizadas, você pode deixar as 10 janelas minimizadas, que o bot vai maximizar uma por uma, e nesse casso você pode ativar a opção fullscreen para true, em ambos os casos você pode delisgar o monitor e fazer outras tarefas. A diferença de uma para outra é a finalidade do uso.

**Comment by robyflc** [comment]
"Você pode colocar 10 janelas distribuidas e abertas na tela, e presencialmente monitorar essas telas, nesse caso essa é funcionalidade de lado a lado."

Agora eu realmente não entendi: se eu vou monitorar presencialmente essas telas, o que o bot faria nesta situação?
