### ISSUE TITLE
run_time_app

### ISSUE THREAD

**Issue by diegolima1996** [newerton/bombcrypto-bot#83]
Newerton, você poderia me explicar melhor sobre run_time_app: 1, e qual a melhor configuração pra ele, pois tô achando que é por conta dele que o bot não coloca os heróis para trabalhar, só fica voltando para atualizar.

**Comment by newerton** [comment]
@diegolial o run_time_app é o tempo sem segundos, que o bot fica tirando print da tela. Esse parametro foi adicionado, para PC/Laptop muito lento.

Por exemplo, eu tenho um Laptop Samsung RV411, de 2GB. Setei o run_time_app para 3, então a cada 3 segundos o bot tira print da tela, para identificar onde o jogo está, se está no mapa, se está na tela principal, se está buscando os heróis.

Para colocar os heróis para trabalhar, você tem que configurar o send_heroes_for_work. Se você colocar [30, 40], o Bot vai buscar os heróis entre 30 até 40 minutos.
