### ISSUE TITLE
Erro Multi Account

### ISSUE THREAD

**Issue by bvieira15** [newerton/bombcrypto-bot#84]
Como faço para utilizar o multi acc?? fica travado assim para mim
![photo_2022-02-05_14-12-35](https://user-images.githubusercontent.com/98408289/152652405-69f50855-e404-4695-a1d7-81d2820415a0.jpg)

**Comment by newerton** [comment]
@bvieira15 Quantos GB tem esse notebook? O bot não está maximizando as janelas?
