### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by caslujpg** [newerton/bombcrypto-bot#88]
na hora que tento executar o programa no linux, nao vai, como se nao reconhecesse, sera que conseguiria me auxiliar?

**Comment by newerton** [comment]
@lucgregor Se estiver usando multiacc, não vai funcionar por enquanto, a biblioteca que faz o reconhecimento das janelas do linux, não identificar todas as janelas ativa.

Agora se estiver usando em 1 conta, o bot está funcionando normal. Consegue me explicar onde o bot está parando?

**Comment by caslujpg** [comment]
consigo te mandar prints, pode ser? se sim, posso mandar por aqui ou pelo seu discord, como preferir

**Comment by newerton** [comment]
@lucgregor Manda no discord Newerton#3507

**Comment by caslujpg** [comment]
acho que agora consegui instalar o python direito mas nao consigo rodar o bot da mesma forma
