### ISSUE TITLE
ModuleNotFoundError: No module named 'git'

### ISSUE THREAD

**Issue by johndavemanuel** [newerton/bombcrypto-bot#90]
After running .\cmd\update_files.bat, it shows an error.

I have a git installed in PC, because I clone this repo for updates

**Comment by newerton** [comment]
@johndavemanuel Auto-update files (requires Git installed)

**Comment by johndavemanuel** [comment]
I have git installed on my pc. I clone the repo in github not download as zip

**Comment by newerton** [comment]
@johndavemanuel Enter in folder, and type git pull

**Comment by johndavemanuel** [comment]
@newerton is this different?

 .\cmd\update_files.bat,

**Comment by newerton** [comment]
> @newerton is this different?
> 
> .\cmd\update_files.bat,

Yes. the update_files.bat clone the repository and replace the files.
