### ISSUE TITLE
Can I request version with Home feature ?

### ISSUE THREAD

**Issue by YanHappy** [newerton/bombcrypto-bot#93]
Hello, This tool is very usefull for me to automation with bombcrypto , 
So , Can you make a version work with home feature. and sent Bcoin amount report frequently not wait for the new map pop up ?

**Comment by newerton** [comment]
@YanHappy I really wanted to implement it, but I don't have any home account to implement this functionality.

**Comment by J3Z1N63R57** [comment]
I have an account with the house if you need one
