### ISSUE TITLE
Refreshs múltiplos 

### ISSUE THREAD

**Issue by kerferber** [newerton/bombcrypto-bot#96]
Primeiramente parabéns pela rápida atualização.

Aqui estou com um pequeno problema...

Algumas vezes, por lentidão na VM, o jogo demora um pouco pra carregar, com isso o bot entende que houve falha no Login e dá refresh...

As vezes isso acontece mais de 10x seguidas até carregar.

Pergunto, de que forma posso aumentar o tempo que o bot leva pra verificar se o login teve sucesso? Obrigado

**Comment by newerton** [comment]
@kerferber Tudo bem? Sabe me dizer em que etapa ocorre a lentidão?

Se é na hora que vai abrir a metamask para o bot clicar no SignIn ou no Loading do jogo?

**Comment by kerferber** [comment]
Aqui ocorre quando está carregando a barra de loading.

A maior parte das vezes carrega rápido, mas as vezes acho que fica um pouco sobrecarregado e demora.. agora por exemplo, está indo assim:

0..5...10......20.....25....30....37....39....40....45%

 e nesse meio tempo ele dá o refresh. As vezes chega nos 100% mas demora tanto que acaba dando o refresh

![Uploading Screenshot_20220223-214928_Telegram.jpg…]()

**Comment by kerferber** [comment]
![Screenshot_20220223-214928_Telegram](https://user-images.githubusercontent.com/95573625/155436511-3b5705ff-a898-4279-b3aa-5d5025882b84.jpg)


Edit: após eu postar essa foto ele conseguiu logar... deu uns 5 ou 6 refreshs apenas. Mas hoje mais cedo deu mais de 20 refreshs. Precisei acessar a Vm, fechar o bot, logar manualmente, e reabrir o bot já logado

**Comment by newerton** [comment]
Você está acompanhando os aviso de manutenção? Hoje foram 2 paradas para manutenção. Antes o loading estava travando em 50%. O bot depois que ele clicar no login da metamask, ele aguarda 1 minuto logar, mais do que isso ou é lentidão da internet ou o jogo está lento. Uso o bot em notebook de 2GB e só tenho problema quando o game entra em manutenção.

**Comment by kerferber** [comment]
Sim sim. Fora do período de manutenção.

Estou me referindo a lentidão mesmo..

Onde mais ou menos posso alterar este tempo de 1 minuto? Pois como relatei, não está sendo suficiente aqui.

Rodo multiaccount em uma vm bem fraca

**Comment by newerton** [comment]
@kerferber Altera esses segundos aqui:

https://github.com/newerton/bombcrypto-bot/blob/main/src/auth.py#L62
https://github.com/newerton/bombcrypto-bot/blob/main/src/auth.py#L95
