### ISSUE TITLE
Multi user and pass

### ISSUE THREAD

**Issue by aroweyen** [newerton/bombcrypto-bot#97]
How can I make the bot enter different username and password for each account?

**Comment by newerton** [comment]
This problem is the same as the telegram report for multiaccount. Initially I will search for a solution, because there are users who have more than 10 accounts, and the bot will not identify which window should use which username and password.

**Comment by aroweyen** [comment]
Maybe identify with browser's profile?
In firefox it shows different images in each profile.

**Comment by newerton** [comment]
@aroweyen Test 3 lib windows recognition of the operating system, they all use the window title, they can't get additional information like the profile name.

**Comment by aroweyen** [comment]
Today's Update now saves username and password so there's no need to type
anymore them anymore whenever I get disconnected.
So how can I change it to click the log in button for username and password
instead of metamask?
