### ISSUE TITLE
Multi Account BUG

### ISSUE THREAD

**Issue by guibess** [newerton/bombcrypto-bot#98]
![image](https://user-images.githubusercontent.com/89614432/155573852-5139ead7-d54a-4729-ae39-abe83bff18e4.png)
abro o bot, e fica nisso

**Comment by newerton** [comment]
@guibess Você ativou a autenticação por usuário e senha?

**Comment by bvieira15** [comment]
Tambem estou com o mesmo problema

**Comment by newerton** [comment]
@bvieira15 Está usando qual sistema operacional e navegador? Testei no Windows 11 e Windows 7 com Chrome e Firefox.

**Comment by pedrowarlock** [comment]
> @guibess Você ativou a autenticação por usuário e senha?

O meu crasha quando desativo o mult account

**Comment by newerton** [comment]
> > @guibess Você ativou a autenticação por usuário e senha?
> 
> O meu crasha quando desativo o mult account

Envia um print aqui do erro
