### ISSUE TITLE
Tempo de espera para metamask

### ISSUE THREAD

**Issue by carlosrcjunior** [newerton/bombcrypto-bot#99]
Cara primeiramente parabéns pelo projeto, eu queria saber se tem algum lugar que eu possa mudar o tempo de espera para assinar a metamask.
O que acontece é que o bot clica em connect to wallet, porém, meu computador demora pra abrir a janela da metamask pedindo pra assinar

**Comment by newerton** [comment]
@carlosrcjunior Eae, ontem teve um usuário que estava com o mesmo problema. Estou achando que as atualizações da metamask está deixando o plugin pesado. Mas você pode alterar os segundos de espera nessas duas linhas aqui:

https://github.com/newerton/bombcrypto-bot/issues/96#issuecomment-1049394784
